### ISSUE TITLE
Ansible 1.9.0.1: unarchive fails with tar archives

### ISSUE THREAD

**Issue by nikut** [ansible/ansible-modules-core#1064]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.0.1 (detached HEAD 29809bb83d) last updated 2015/04/02 16:01:22 (GMT +300)
  lib/ansible/modules/core: (detached HEAD d56c219a15) last updated 2015/04/02 16:01:22 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD a7c8224930) last updated 2015/04/02 16:01:22 (GMT +300)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/02 16:01:22 (GMT +300)
  v2/ansible/modules/extras: (detached HEAD 46e316a20a) last updated 2015/04/02 16:01:22 (GMT +300)
  configured module search path = /home/thedealer/ansible/library
```
##### Environment:

Ansible host: CentOS release 5.9 (Final)
Target hosts: Red Hat Enterprise Linux Server release 5.11 (Tikanga), CentOS release 6.4 (Final)
##### Summary:

After upgrading from Ansible 1.8.4 to 1.9.0.1 unarchive no longer works with tar archives. Due to a logic error in TgzArchive.is_unarchived() it never unpacks the archive and fails when trying to stat nonexistent files. 

The problem is that in the case of an empty target directory `gtar --diff` only reports one difference: `.: Mode differs`. Because is_unarchived() ignores mode, uid and gid differences and no other differences are reported, it thinks the archive was already unarchived.
##### Steps To Reproduce:

Test tarball:

```
(ansible) ansible@dealer:/tmp > tar ztvf test.tar.gz
drwxrwxr-x ansible/ansible 0 2015-04-02 15:47:03 ./
drwxrwxr-x ansible/ansible 0 2015-04-02 15:47:05 ./foo/
-rw-rw-r-- ansible/ansible 0 2015-04-02 15:47:05 ./foo/bar
```

Playbook:

```

---
- hosts: testhost
  sudo: yes
  tasks:
    - file: path=/tmp/testdir state=directory
    - unarchive: src=/tmp/test.tar.gz dest=/tmp/testdir owner=root group=root mode=0755
```
##### Expected Results:

This is what happens on 1.8.4.

```

PLAY [testhost] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [testhost]

TASK: [file path=/tmp/testdir state=directory] ******************************** 
changed: [testhost]

TASK: [unarchive src=/tmp/test.tar.gz dest=/tmp/testdir owner=root group=root mode=0755] *** 
changed: [testhost]

PLAY RECAP ******************************************************************** 
testhost                      : ok=3    changed=2    unreachable=0    failed=0   

```

```
root@testhost:/tmp# find /tmp/testdir
/tmp/testdir
/tmp/testdir/foo
/tmp/testdir/foo/bar
```
##### Actual Results:

```
PLAY [testhost] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [testhost]

TASK: [file path=/tmp/testdir state=directory] ******************************** 
changed: [testhost]

TASK: [unarchive src=/tmp/test.tar.gz dest=/tmp/testdir owner=root group=root mode=0755] *** 
failed: [testhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-cexuozhwjtqtkudqoenphnsndjqjvmuh
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1427981575.48-179470201120113/unarchive", line 1890, in ?
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1427981575.48-179470201120113/unarchive", line 289, in main
    res_args['changed'] = module.set_fs_attributes_if_different(file_args, res_args['changed'])
  File "/home/ansible/.ansible/tmp/ansible-tmp-1427981575.48-179470201120113/unarchive", line 1083, in set_fs_attributes_if_different
    changed = self.set_owner_if_different(
  File "/home/ansible/.ansible/tmp/ansible-tmp-1427981575.48-179470201120113/unarchive", line 886, in set_owner_if_different
    orig_uid, orig_gid = self.user_and_group(path)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1427981575.48-179470201120113/unarchive", line 813, in user_and_group
    st = os.lstat(filename)
OSError: [Errno 2] No such file or directory: '/tmp/testdir/./foo/'
OpenSSH_6.7p1, OpenSSL 1.0.1j 15 Oct 2014
debug1: Reading configuration data /home/ansible/.ssh/config
debug1: /home/ansible/.ssh/config line 10: Applying options for *
debug1: Reading configuration data /usr/local/openssh-6.7p1/etc/ssh_config
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to testhost closed.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/test-unarchive.retry

testhost                      : ok=2    changed=1    unreachable=0    failed=1   

```

```
root@testhost:/tmp# find /tmp/testdir
/tmp/testdir
```

**Comment by nikut** [comment]
An extra detail that may explain how this slipped through testing. This bug is only triggered when:
- the mode of the target directory differs from the mode of the root of the tar ball AND
- `mode=...` is set in the unarchive task (and thus the mode difference is ignored)

From this it follows that one can work around this bug by either:
- creating the target directory with the same mode that the root of the tar ball has OR
- removing any explicit `mode=...` from the unarchive task
