### ISSUE TITLE
ini_file fails with backup: yes if the file doesn't exist. 

### ISSUE THREAD

**Issue by magicrobotmonkey** [ansible/ansible-modules-core#1096]
Using ini_file to create and populate an ini file with backup turned on causes:

```
Traceback (most recent call last):
  File "/home/lupe/.ansible/tmp/ansible-tmp-1428345708.72-245168330213743/ini_file", line 1803, in <module>
    main()
  File "/home/lupe/.ansible/tmp/ansible-tmp-1428345708.72-245168330213743/ini_file", line 199, in main
    changed = do_ini(module, dest, section, option, value, state, backup)
  File "/home/lupe/.ansible/tmp/ansible-tmp-1428345708.72-245168330213743/ini_file", line 149, in do_ini
    module.backup_local(filename)
  File "/home/lupe/.ansible/tmp/ansible-tmp-1428345708.72-245168330213743/ini_file", line 1512, in backup_local
    shutil.copy2(fn, backupdest)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/etc/dna_web/settings.ini'
```

**Comment by tristanfisher** [comment]
I believe that this rightfully errors out.  What's the purpose of "backing up" an empty ini file?  What utility would a copy of an empty file give you?

**Comment by magicrobotmonkey** [comment]
The next time this playbook runs, with  a change to the settings, I'd like the file to be backed up. I feel as though this is not an uncommon thing to happen. You're standing up a service on a box and the ini_file is created. Later you may come back and change the service, and you'd like to have a backup of your settings.

**Comment by tristanfisher** [comment]
I misunderstood (sorry).  I agree that you should be able to leave `backup: yes` in your first call to creating an `ini_file` using the relevant module.

**Comment by bcoca** [comment]
see if this PR fixes at least the traceback https://github.com/ansible/ansible/pull/10629
