### ISSUE TITLE
pip module fails on already installed packages

### ISSUE THREAD

**Issue by kevzettler** [ansible/ansible-modules-core#1099]
```
failed: [104.131.151.44] => {"cmd": "/usr/bin/pip install docker-py", "failed": true}
msg:
:stderr: Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead


FATAL: all hosts have already failed -- aborting
```

using the pip module to install docker_py. It seems to install on a fresh run however subsequent runs throw this error

**Comment by sivel** [comment]
It sounds like you have mismatched versions of pip and requests.

If possible I would recommend upgrading pip.  There are various mentions of this bug in google searches.

It is not related to ansible.
