### ISSUE TITLE
Starting a container fails with "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by soupdiver** [ansible/ansible-modules-core#1188]
My playbook:

``` yaml

---
- name: pull redis image
  shell: "docker pull redis:{{ hubot_redis_version }}"

- name: start redis container
  docker:
    image: "redis:{{ hubot_redis_version }}"
    name: redis-hubot
    state: running
```

where `hubot_redis_version` is `3.0`

This will result in:

``` bash
PLAY [hubot] ******************************************************************

GATHERING FACTS ***************************************************************
ok: [coconut]

TASK: [hubot | pull redis image] **********************************************
changed: [coconut]

TASK: [hubot | start redis container] *****************************************
failed: [coconut] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1429750315.49-205659985739734/docker", line 3104, in <module>
    main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1429750315.49-205659985739734/docker", line 1478, in main
    started(manager, containers, count, name)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1429750315.49-205659985739734/docker", line 1327, in started
    containers.refresh()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1429750315.49-205659985739734/docker", line 1288, in refresh
    self.deployed = self.manager.get_deployed_containers()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1429750315.49-205659985739734/docker", line 1122, in get_deployed_containers
    matches = name in i.get('Names', [])
TypeError: argument of type 'NoneType' is not iterable
```

Env:

``` bash
felix:ansible felix$ ansible --version
ansible 1.9.0.1
```

``` bash
ansible@coconut:~$ docker -v
Docker version 1.6.0, build 4749651
```

**Comment by vpetersson** [comment]
+1

**Comment by john99jacobs** [comment]
+1

**Comment by TrustNoOne** [comment]
+1

**Comment by abadger** [comment]
I was unable to replicate this (set hubot_redis_version to latest since I don't know what version you used).  However, I can see how we could get that traceback from that line of code so I made a change to that which might fix this.

If you can test the commit I just pushed above that would be great!  I close this in a few days if I don't hear back.

**Comment by soupdiver** [comment]
@abadger what do you mean with `set hubot_redis_version to latest since I don't know what version you used`?

I did mention that I used `3.0` which is also the latest.

Or do you mean the version of something else?

**Comment by abadger** [comment]
@soupdiver ah, my bad.  I didn't see that that you had written that when I was testing the issue earlier.  Does it work for you now?

**Comment by soupdiver** [comment]
I tested with 

```
felix:~ felix$ ansible --version
ansible 1.9.1
```

and was able to start containers again. Looks good :)

**Comment by sitamet** [comment]
I run into this same problem when trying to start 2 containers in parallel.

I have: `ansible 1.9.1`

```
failed: [a] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ufdlljojxmtjazaqhpqdgtgagthpwmtp
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 3110, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1484, in main
    stopped(manager, containers, count, name)
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1375, in stopped
    containers.refresh()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1288, in refresh
    self.deployed = self.manager.get_deployed_containers()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1122, in get_deployed_containers
    matches = name in i.get('Names', [])
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by bcoca** [comment]
have you tested against current devel? the line in the traceback seems to have been completely rewritten

**Comment by sitamet** [comment]
Thanks bcoca!
The devel version, runs perfect.

**Comment by bcoca** [comment]
so closing this as ti seems to be fixed in newer versions.
