### ISSUE TITLE
Unable to get rds parameter groups to work

### ISSUE THREAD

**Issue by hyperfocus1338** [ansible/ansible-modules-core#1216]
**Issue Type:**

Bug report

**Ansible Version:**

ansible 1.9.0.1

**Environment:**

Mac OSX 10.10.3

**Summary:**

Error 1:

```
failed: [localhost] => {"failed": true}
msg: The parameter DBParameterGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
```

Error 2:

```
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ndavmmqzhdryxvlfgbbnyqukkgcfnpud
Traceback (most recent call last):
  File "/Users/hyper/.ansible/tmp/ansible-tmp-1430238680.28-166914816730517/rds_param_group", line 2107, in <module>
    main()
  File "/Users/hyper/.ansible/tmp/ansible-tmp-1430238680.28-166914816730517/rds_param_group", line 290, in main
    changed_params, group_params = modify_group(next_group, group_params, immediate)
  File "/Users/hyper/.ansible/tmp/ansible-tmp-1430238680.28-166914816730517/rds_param_group", line 212, in modify_group
    changed[key] = {'old': param.value, 'new': new_value}
  File "/Library/Python/2.7/site-packages/boto/rds/parametergroup.py", line 184, in get_value
    self._set_integer_value(self._value)
  File "/Library/Python/2.7/site-packages/boto/rds/parametergroup.py", line 146, in _set_integer_value
    value = int(value)
ValueError: invalid literal for int() with base 10: '{DBInstanceClassMemory/12582880}'


FATAL: all hosts have already failed -- aborting
```

**Steps To Reproduce:**

run `sudo ansible-playbook site.yml -i inventory/localhost -t aws_create_rds_parameter_group`

with play below:

```
- name: create rds parameter group
  rds_param_group: 
      name: "{{ rds_parameter_group_name }}"
      description: "{{ rds_parameter_group_description }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ rds_region }}"
      engine: "{{ rds_engine }}"
      state: present

      params:
         max_allowed_packet: "{{ rds_max_allowed_packet }}"
         max_connections: "{{ rds_max_connections }}"
         table_definition_cache: "{{ rds_table_definition_cache }}"
         table_open_cache: "{{ rds_table_open_cache }}"
```

variables:

```
rds_parameter_group_name: performance-optimized
rds_parameter_group_description: "performance configuration for 1g instance"
aws_access_key: xxx
aws_secret_key: xxx
rds_region: eu-west-1
rds_engine: mysql5.6
rds_max_allowed_packet: "16M"
rds_max_connections: "500"
rds_table_definition_cache: "1024"
rds_table_open_cache: "2048"
```

**Expected Results:**

Simply work.

**Actual Results:**

Adds the parameter groups with name `performance-optimzed` but not `performance_optimized`, doesn't add actual parameters.

**Comment by jeffreykaplan** [comment]
Seeing the same error when using a variable formula such as "{DBInstanceClassMemory/32}". 

```
failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/jkaplan/.ansible/tmp/ansible-tmp-1430406337.15-241558244506727/rds_param_group", line 2113, in <module>
    main()
  File "/home/jkaplan/.ansible/tmp/ansible-tmp-1430406337.15-241558244506727/rds_param_group", line 291, in main
    changed_params, group_params = modify_group(next_group, group_params, immediate)
  File "/home/jkaplan/.ansible/tmp/ansible-tmp-1430406337.15-241558244506727/rds_param_group", line 215, in modify_group
    set_parameter(param, new_value, immediate)
  File "/home/jkaplan/.ansible/tmp/ansible-tmp-1430406337.15-241558244506727/rds_param_group", line 184, in set_parameter
    param.value = converted_value
  File "/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py", line 171, in set_value
    self._set_integer_value(value)
  File "/usr/local/lib/python2.7/dist-packages/boto/rds/parametergroup.py", line 146, in _set_integer_value
    value = int(value)
ValueError: invalid literal for int() with base 10: '{DBInstanceClassMemory/32}'


FATAL: all hosts have already failed -- aborting
```

Ansible 1.9.1
Boto 2.38.0
Linux Mint 17.1

**Comment by bcoca** [comment]
why are you running ansible under sudo?

**Comment by bcoca** [comment]
also i don't understand why you expect anything with performance_optimized when you specify performance-optimized

**Comment by hyperfocus1338** [comment]
Why not use sudo? Don't want to mess up my system by accident. And further clarification on your second point, it fails to create the parameter group with name `performance_optimized` while it succeeds  with name `performance-optimized`. 

With succeeds I mean the parameter group does appear in the aws dashboard, while at the same time ansible failed with the mentioned error. Does still fail to add the parameter groups though.

**Comment by bcoca** [comment]
The sudo question was a curiosity ... not sure how that avoids messing your system as it grants you superuser when you do not need it for this task, this is an remote API call and your local user should not matter.

The error looks like we pass something incorrect to the boto library, I have not had time to dig in deep but this is on my list to revise.

**Comment by samdoiron** [comment]
Error is here https://github.com/ansible/ansible-modules-core/blob/35703caf6fb09598c2c0538f4690af0b8f606dce/cloud/amazon/rds_param_group.py#L186-199

There is a try / except to catch the ValueError thrown by boto and reassign old_value, but then it just uses param.value anyway instead of old_value.

**Comment by bcoca** [comment]
closing by merge of #1254

**Comment by hyperfocus1338** [comment]
Nice work guys. @bcoca understood about the sudo thing, thanks for explanation.
