### ISSUE TITLE
Openstack: global name 'HAVE_NOVACLIENT' is not defined

### ISSUE THREAD

**Issue by sky-shiny** [ansible/ansible-modules-core#1364]
Creating a keypair fails with latest branch.  

```
TASK: [Create a keypair] ******************************************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
/Users/mca18/.virtualenvs/playbook-test/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
Traceback (most recent call last):
  File "/Users/mca18/.ansible/tmp/ansible-tmp-1432044877.41-79531016887355/nova_keypair", line 1860, in <module>
    main()
  File "/Users/mca18/.ansible/tmp/ansible-tmp-1432044877.41-79531016887355/nova_keypair", line 100, in main
    if not HAVE_NOVACLIENT:
NameError: global name 'HAVE_NOVACLIENT' is not defined
```

**Comment by sky-shiny** [comment]
https://github.com/ansible/ansible-modules-core/pull/1365

**Comment by bcoca** [comment]
fixed via https://github.com/ansible/ansible-modules-core/commit/5011593ee398895d25c8078f3bf073442f4fa33d
