### ISSUE TITLE
Docker module crashes

### ISSUE THREAD

**Issue by olvesh** [ansible/ansible-modules-core#1373]
Issue Type: Bug Report.

Ansible Version: Ansible 1.9.1

Ansible Configuration: No Changes

Environment: Ubuntu Trusty (from Mac OSX master)

Summary:

Is this bug ansible/ansible#7363 reintroduced somehow? 

```
TASK: [esnode | Install elastic search docker image] **************************
failed: [10.0.3.127] => {"failed": true, "parsed": false}
BECOME-SUCCESS-jzjqudcracyglzuadcdbbnlkuxauglzj
Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432110718.82-246882878724151/docker", line 3110, in <module>
    main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432110718.82-246882878724151/docker", line 1478, in main
    started(manager, containers, count, name)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432110718.82-246882878724151/docker", line 1327, in started
    containers.refresh()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432110718.82-246882878724151/docker", line 1288, in refresh
    self.deployed = self.manager.get_deployed_containers()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1432110718.82-246882878724151/docker", line 1122, in get_deployed_containers
    matches = name in i.get('Names', [])
TypeError: argument of type 'NoneType' is not iterable
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011


FATAL: all hosts have already failed -- aborting
```

After removing a few images in docker it worked again (`docker rm 8a1b8314f2f9 133eb0117f4e`). 

```
ubuntu@ip-10-0-3-127:~$ docker ps -a
CONTAINER ID        IMAGE                             COMMAND                CREATED             STATUS                          PORTS                                                                                                        NAMES
133eb0117f4e        progrium/consul:latest            "\"/bin/bash -c 'cur   25 minutes ago      Dead
c99ebf602e91        nginx:latest                      "nginx -g 'daemon of   4 days ago          Up 26 minutes                   443/tcp, 10.0.3.127:9080->80/tcp                                                                             nginx
8a1b8314f2f9        nginx:latest                      "nginx -g 'daemon of   4 days ago                                                                                                                                                       pensive_einstein
0c897c49a084        elasticsearch:1.5.2               "/docker-entrypoint.   4 days ago          Up 26 minutes                                                                                                                                elasticsearch
c951bcc64c98        vimond/kafka:0.7.2                "/start.sh"            4 days ago          Restarting (0) 11 minutes ago   10.0.3.127:7203->7203/tcp, 10.0.3.127:9092->9092/tcp                                                         kafka-07
8cb2ddc2050e        vimond/zk-exhibitor:3.4.6_1.5.5   "bash -ex /opt/exhib   5 days ago          Up 26 minutes                   10.0.3.127:2181->2181/tcp, 10.0.3.127:2888->2888/tcp, 10.0.3.127:3888->3888/tcp, 10.0.3.127:8181->8181/tcp   zk-exhibitor
0c09e20d61d7        gliderlabs/registrator:latest     "/bin/registrator co   5 days ago          Up 26 minutes                                                                                                                                registrator
20d6dd72d8a9        progrium/consul:latest            "/bin/start -server    5 days ago          Up 26 minutes                                                                                                                                consul
```

The offending part of generated python file on the host was (i added [l 1122] for line number ref):

``` python
    def get_deployed_containers(self):
        """
        Return any matching containers that are already present.
        """

        command = self.module.params.get('command')
        if command:
            command = command.strip()
        name = self.module.params.get('name')
        if name and not name.startswith('/'):
            name = '/' + name
        deployed = []

        # "images" will be a collection of equivalent "name:tag" image names
        # that map to the same Docker image.
        inspected = self.get_inspect_image()
        if inspected:
            repo_tags = self.get_image_repo_tags()
        else:
            image, tag = get_split_image_tag(self.module.params.get('image'))
            repo_tags = [':'.join([image, tag])]

        for i in self.client.containers(all=True):
            running_image = i['Image']
            running_command = i['Command'].strip()
            match = False

            if name:
[l 1122]        matches = name in i.get('Names', [])
            else:
                image_matches = running_image in repo_tags

                # if a container has an entrypoint, `command` will actually equal
                # '{} {}'.format(entrypoint, command)
                command_matches = (not command or running_command.endswith(command))

                matches = image_matches and command_matches

            if matches:
                details = self.client.inspect_container(i['Id'])
                details = _docker_id_quirk(details)

                deployed.append(details)

        return deployed
```

**Comment by olvesh** [comment]
Currently I have this workaround before every play:

``` yaml
  pre_tasks:
    - shell: "docker ps -a | grep Dead | cut -d ' ' -f 1 | xargs docker rm"
      ignore_errors: yes
```

**Comment by sitamet** [comment]
I run into this same problem when trying to start 2 containers in parallel.

I have: `ansible 1.9.1`

```
failed: [a] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ufdlljojxmtjazaqhpqdgtgagthpwmtp
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 3110, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1484, in main
    stopped(manager, containers, count, name)
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1375, in stopped
    containers.refresh()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1288, in refresh
    self.deployed = self.manager.get_deployed_containers()
  File "/root/.ansible/tmp/ansible-tmp-1433442487.92-73386371866624/docker", line 1122, in get_deployed_containers
    matches = name in i.get('Names', [])
TypeError: argument of type 'NoneType' is not iterable
```

This same bug is reported in [ansible-modules-core/issues/1188](https://github.com/ansible/ansible-modules-core/issues/1188)
