### ISSUE TITLE
UnboundLocalError apt module

### ISSUE THREAD

**Issue by malinoff** [ansible/ansible-modules-core#1499]
##### Issue Type:

Bug report.
##### Ansible Version:

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

Not related.
##### Environment:

Debian 8, but I'm sure this will be reproduced on any deb-based distro.
##### Summary:

`UnboundLocalError` is raised when trying to install package from local path which is not actually deb package and is directory instead.
##### Steps To Reproduce:

Accidentally copy directory instead of deb package on remote machine, then try to install it.
Sample playbook:

```

---
- hosts: all
  tasks:
    - file: path=/tmp/imapackage.pkg state=directory
    - apt: deb=/tmp/imapackage.pkg
```
##### Expected Results:

Some error about `imapackage.pkg` not being actually a package.
##### Actual Results:

```
PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [example]

TASK: [file path=/tmp/imapackage.pkg state=directory] ************************* 
changed: [example]

TASK: [apt deb=/tmp/imapackage.pkg] ******************************************* 
failed: [example] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/admin/.ansible/tmp/ansible-tmp-1433993626.3-239347679071120/apt", line 2240, in <module>
    main()
  File "/home/admin/.ansible/tmp/ansible-tmp-1433993626.3-239347679071120/apt", line 602, in main
    force=force_yes, dpkg_options=p['dpkg_options'])
  File "/home/admin/.ansible/tmp/ansible-tmp-1433993626.3-239347679071120/apt", line 369, in install_deb
    m.fail_json(msg="Error: %s\nSystem Error: %s" % (pkg._failure_string,str(e)))
UnboundLocalError: local variable 'pkg' referenced before assignment
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /var/lib/jenkins/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to example closed.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/lib/jenkins/sample.retry

example                : ok=2    changed=1    unreachable=0    failed=1 
```

**Comment by bcoca** [comment]
try the version in devel, this seems to have already been fixed.

**Comment by peterfarrell** [comment]
I'm seeing the same issue with Ansible 1.9.2.

**Comment by gdepourtales** [comment]
Same on v1.9.2 (```my_package_path``` referencing a valid local file) :
```
- name: apt
  apt: deb={{my_package_path}} state=present
  sudo: yes
```

**Comment by Hirandil** [comment]
Hi, I've also encountered this error with ansible 1.9.2 on Ubuntu as I was trying to install a debian package with the apt module. Are there any news on this?

**Comment by bcoca** [comment]
test with my commit, it should come  out with 1.9.3 and 2.0

**Comment by Hirandil** [comment]
It is indeed fixed, thanks a lot !
