### ISSUE TITLE
Ansible having issues with pycryto lib

### ISSUE THREAD

**Issue by philipperibeiro** [ansible/ansible-modules-core#1549]
I have the following script:
 create_dynamic_template(om_ip_address, playbook="deploy_ec2.yml"):
     inventory_template = jinja2.Template(inventory)
     rendered_inventory = inventory_template.render({
          'om_ip_address' : om_ip_address,
          # add the any other variable here
     })

```
 # Create a temporary file and write the template string to it
 hosts = NamedTemporaryFile(delete=False)
 hosts.write(rendered_inventory)
 hosts.close()
 playbook_path = os.path.join(config.ANSIBLE_PLAYBOOKS, playbook)
 key_file = os.path.join(os.path.expanduser("~"), '.ssh/id_rsa')
 inventory_obj = Inventory(host_list=[hosts.name], vault_password="Hello1234")
 pb = PlayBook(
        playbook=playbook_path,
        remote_user='deploy',
        inventory=inventory_obj,
        callbacks=playbook_cb,
        runner_callbacks=runner_cb,
        stats=stats,
        private_key_file=key_file,
 )

 results = pb.run()
 # Ensure the stats callback is called
 playbook_cb.on_stats(pb.stats)
 os.remove(hosts.name)

 print results
```

 if **name** == "**main**":
     create_dynamic_template("10.20.30.40", "deploy_ec2.yml")

When I execute my script ansible_api.py I'm getting the following error: 

root@fdsdev:~/fds-src/source/test/testlib# python ansible_api.py
Traceback (most recent call last):
  File "ansible_api.py", line 90, in <module>
    create_dynamic_template("10.20.30.40", "deploy_ec2.yml")
  File "ansible_api.py", line 81, in create_dynamic_template
    results = pb.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/**init**.py", line 310, in run
    play = Play(self, play_ds, play_basedir, vault_password=self.vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 99, in **init**
    processed_vars_files = self._update_vars_files_for_host(None)
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 946, in _update_vars_files_for_host
    if process_files(filename, filename2, filename3, filename4, host=host):
  File "/usr/local/lib/python2.7/dist-packages/ansible/playbook/play.py", line 888, in process_files
    data = utils.parse_yaml_from_file(filename4, vault_password=self.vault_password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 774, in parse_yaml_from_file
    data = vault.decrypt(data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 136, in decrypt
    data = this_cipher.decrypt(data, self.password)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 555, in decrypt
    key1, key2, iv = self.gen_key_initctr(password, salt)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/vault.py", line 505, in gen_key_initctr
    count=10000, prf=pbkdf2_prf)
  File "/usr/lib/python2.7/dist-packages/Crypto/Protocol/KDF.py", line 110, in PBKDF2
    password = tobytes(password)
  File "/usr/lib/python2.7/dist-packages/Crypto/Util/py3compat.py", line 85, in tobytes
    return ''.join(s)
TypeError

inventory is a string template so I can create dynamic inventory files. 
Ansible version is 1.9.1.  I have gone through some pain in order to figure this out, with no success. Help?

**Comment by bennojoy** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

since this is more a development question ansible-devel mailing list or ansible-devel irc channel should be more suited.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
