### ISSUE TITLE
Linode action fail: The requested class does not exist

### ISSUE THREAD

**Issue by arturmartins** [ansible/ansible-modules-core#1727]
Hi,

I have been trying to create servers on linode, but I have been unsuccessful so far (actually since 30th April).
### Current environment

```
$ pip list | grep linode
linode (0.4)
linode-python (1.2)

# ansible --version
ansible 1.9.2
    configured module search path = None
```
### Playbook:

Created the following playbook file `/etc/ansible/linode-test.yml`:

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create linode server
    linode:
     name: linode-test1
     plan: 1
     datacenter: 6
     distribution: 124
     password: 'YOUR_API_KEY_HERE'
     ssh_pub_key: 'YOUR_SSH_PUBKEY_HERE'
     swap: 512
     wait: yes
     wait_timeout: 600
     state: present
```

Note: Using LINODE_API_KEY env variable instead defining api_key.
### Playbook run

`# ansible-playbook /etc/ansible/linode-test.yml`

```
PLAY [localhost] **************************************************************

TASK: [Create linode server] **************************************************
failed: [localhost] => {"failed": true, "parsed": false}
[test_echo] The requested class does not existTraceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1436886321.73-258368237544829/linode", line 2098, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1436886321.73-258368237544829/linode", line 485, in main
    module.fail_json(msg = '%s' % e.value[0]['ERRORMESSAGE'])
AttributeError: 'LinodeException' object has no attribute 'value'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/user/linode-test.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

The errors _The requested class does not exist_ and  _'LinodeException' object has no attribute 'value'_ seem to indicate there is a problem with the linode module?

Or am I doing something wrong here?

Cheers,
Artur

**Comment by arturmartins** [comment]
I think I managed to isolate where the problem resides:

$ `python`

```
>>> from linode import api as linode_api  
>>> api = linode_api.Api('API_KEY_HERE')
>>> api.test_echo()
[test_echo] The requested class does not existTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/linode/api.py", line 27, in __call__
    return self.klass._worker_func(self.path, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/linode/api.py", line 76, in _worker_func
    return self._request(api_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/linode/api.py", line 69, in _request
    raise LinodeException(content.get('ACTION'), content.get('ERRORARRAY'))
linode.api.LinodeException
```

Code here: https://github.com/ghickman/linode/blob/master/linode/api.py

**Comment by bcoca** [comment]
so this is probably 2 errors, the first exception and then the handling of the exception which obscures the original one.

I'm going to guess this is mainly because the linode.py has changed a lot from the original version used when the module was built.

**Comment by bcoca** [comment]
actually, it looks like you are using a completely different linode library, this is the one you want:

https://pypi.python.org/pypi/linode-python/1.1.1 
or at source
https://github.com/tjfontaine/linode-python

**Comment by arturmartins** [comment]
Hi bcoca,

Both were installed:

```
$ pip list | grep linode
linode (0.4)
linode-python (1.2)
```

Uninstalled linode module (it was probably because of a dependency?) `pip uninstall linode`

Now the result is:

```
# ansible-playbook linode-test.yml

PLAY [localhost] **************************************************************

TASK: [Create linode server] **************************************************
failed: [localhost] => {"failed": true, "parsed": false}
failed=True msg='linode-python required for this module'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/user/linode-test.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by arturmartins** [comment]
Ok, understood the problem. `linode` and `linode-python` create the same folder `/usr/local/lib/python2.7/dist-packages/linode`

How to fix:
1. Uninstall both:

```
pip uninstall -v linode
pip uninstall -v linode-python
```
1. Install again `linode-python`:

```
pip install -v linode-python
```
