### ISSUE TITLE
error when using profile under route53

### ISSUE THREAD

**Issue by glnds** [ansible/ansible-modules-core#1901]
**Issue Type:** Bug Report

**Ansible Version:**  1.9.2

**boto version:** 2.38.0

**Ansible Configuration:** nothing special

**Environment:** OX 10.10.4

**Summary:**

When specifying **profile** and **region** the playbook throws an error. If using AWS environment variables to connect to AWS the playbook runs fine.

**Steps To Reproduce:**

playbook:

```
# vim:ft=ansible:

---

- name: Set DNS Record for New Instance
    route53:
      profile: "{{ profile }}"
      region: "{{ region }}"
      command: create
      zone: example.be
      record: ansible.example.be
      type: A
      ttl: 7200
      value: "{{ eip.public_ip }}"
```

**Expected Results:**

```
TASK: [Set DNS Record for New Instance] ***************************************

changed: [localhost]

PLAY RECAP ********************************************************************
```

**Actual Results**:

```
TASK: [Set DNS Record for New Instance] ***************************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439288241.09-151779888771650/route53", line 2147, in <module>
    main()
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439288241.09-151779888771650/route53", line 227, in main
    ec2_url, aws_access_key, aws_secret_key, region = get_ec2_creds(module)
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439288241.09-151779888771650/route53", line 2100, in get_ec2_creds
    region, ec2_url, boto_params = get_aws_connection_info(module)
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439288241.09-151779888771650/route53", line 2087, in get_aws_connection_info
    if not boto_supports_profile_name():
  File "/Users/glnd/.ansible/tmp/ansible-tmp-1439288241.09-151779888771650/route53", line 2018, in boto_supports_profile_name
    return hasattr(boto.ec2.EC2Connection, 'profile_name')
AttributeError: 'module' object has no attribute 'ec2'


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
```

**Comment by Seraf** [comment]
Hello, same problem here.

Subscribing

**Comment by glnds** [comment]
Same problem with the iam_policy module. It seems to be a more general problem with the ec2 modules.
if i use:

```
export AWS_ACCESS_KEY_ID=...
export AWS_SECRET_ACCESS_KEY=...
export AWS_REGION=...
```

It works fine

**Comment by jonhadfield** [comment]
I've submitted a PR for the route53 issue in ansible 1.9.
It seems to be the same issue in 2.0 for the iam module (missing import in the iam.py module) so will  and get a PR out for that and any others affected.

**Comment by willthames** [comment]
I've added a comment to #2405 for my suggested fix.

**Comment by stephanadler** [comment]
I am on stable-2.0.0.1 and this problem seems to remain. In my case I try to use the dynamodb_table module.
