### ISSUE TITLE
user_module doesn't with with OS X

### ISSUE THREAD

**Issue by anthonygreen** [ansible/ansible-modules-core#1924]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
##### Environment:

Running from: OS X 10.95
Managing: OS X 10.10.2
##### Summary:

user_module doesn't work with OS X
##### Steps To Reproduce:

Run the Ansible task:

```
- name: Add jenkins user
  user: name=jenkins comment="Jenkins" password=password
  sudo: yes
```

results in the failure

```
failed: [jenkins_slave_osx] => {"failed": true, "parsed": false}

BECOME-SUCCESS-wkvlwsejbiklrkcqrqgtsjtxwjgxqhfy
Traceback (most recent call last):
  File "/Users/mediaplayout/.ansible/tmp/ansible-tmp-1439808934.63-115705961875430/user", line 3735, in <module>
    main()
  File "/Users/mediaplayout/.ansible/tmp/ansible-tmp-1439808934.63-115705961875430/user", line 2088, in main
    info = user.user_info()
  File "/Users/mediaplayout/.ansible/tmp/ansible-tmp-1439808934.63-115705961875430/user", line 536, in user_info
    info = self.get_pwd_info()
  File "/Users/mediaplayout/.ansible/tmp/ansible-tmp-1439808934.63-115705961875430/user", line 531, in get_pwd_info
    return list(pwd.getpwnam(self.name))
KeyError: 'getpwnam(): name not found: jenkins'
```

**Comment by thudry** [comment]
Hi 

I'm unable to reproduce your problem.

Ansible Version:
ansible 1.9.2

Environment:
OS X 10.10.5

Have you try with the devel ?

**Comment by anthonygreen** [comment]
Works with 1.9.3.rc1
