### ISSUE TITLE
  quantum_router attempts to hit wrong auth url

### ISSUE THREAD

**Issue by dwcramer** [ansible/ansible-modules-core#2112]
When I attempt to create a new router using quantum_router, I get the following error:

```
TASK: [prep_tenant | Create a router] *****************************************
<localhost> REMOTE_MODULE quantum_router name=iotsprouter
<localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279 && echo $HOME/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279']
<localhost> PUT /var/folders/25/9g455r414513s9bhl85qg3vm0000gn/T/tmpstcU9d TO /Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router
<localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 ./venv/bin/python /Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router']
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 1916, in <module>
    main()
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 188, in main
    _set_tenant_id(module)
  File "/Users/davcrame/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router", line 137, in _set_tenant_id
    for tenant in _os_keystone.tenants.list():
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/v2_0/tenants.py", line 123, in list
    tenant_list = self._list('/tenants%s' % query, 'tenants')
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/base.py", line 113, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
    return self.session.request(url, method, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/utils.py", line 336, in inner
    return func(*args, **kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/session.py", line 382, in request
    resp = send(**kwargs)
  File "/Users/davcrame/dsx/ansible-tools-setup/venv/lib/python2.7/site-packages/keystoneclient/session.py", line 426, in _send_request
    raise exceptions.ConnectionRefused(msg)
keystoneclient.openstack.common.apiclient.exceptions.ConnectionRefused: Unable to establish connection to https://int.us-internal-1.cloud.cisco.com:35357/v2.0/tenants

FATAL: all hosts have already failed -- aborting
```

Inside ~/.ansible/tmp/ansible-tmp-1442611749.49-115695082379279/quantum_router, I see the following lines, indicating that it has picked up the correct value from $OS_AUTH_URL:

```
MODULE_ARGS = "login_username=davcrame login_password='XXXXX' auth_url=https://us-internal-1.cloud.cisco.com:5000/v2.0 login_tenant_name=iotsp-internal-us-internal-1 tenant_name=iotsp-internal-us-internal-1 name=iotsprouter "
```

**Comment by dwcramer** [comment]
I should do some more research on this. It appears to be a problem with our OpenStack deployment.
