### ISSUE TITLE
Traceback in 'raw' module

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-modules-core#2213]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel
##### Ansible Configuration:

Default configuration
##### Environment:

Debian, Ubuntu
##### Summary:

Raw module returns traceback on unicode error.
##### Steps To Reproduce:

```
- hosts: all
  become: True

  tasks:
    - raw: apt-get update
```
##### Expected Results:

Raw command is executed without issues.
##### Actual Results:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 118, in run
    res = self._execute()
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 343, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/action/raw.py", line 34, in run
    result = self._low_level_execute_command(self._task.args.get('_raw_params'), executable=executable)
  File "/usr/lib/pymodules/python2.7/ansible/plugins/action/__init__.py", line 489, in _low_level_execute_command
    out = to_unicode(stdout, errors='strict')
  File "/usr/lib/pymodules/python2.7/ansible/utils/unicode.py", line 100, in to_unicode
    return text_type(obj, 'utf-8', errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 1746: invalid continuation byte

fatal: [hostname]: FAILED! => {"failed": true, "stdout": ""}
```

**Comment by abadger** [comment]
Fixed via https://github.com/ansible/ansible/commit/97e8d25eb4cef73cbde71a1ecaf1fcab96c94cc8
