### ISSUE TITLE
apt with_items throws a TypeError: argument of type 'NoneType' is not iterable on 2.0

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible-modules-core#2300]
I'm running Ansible 2.0 from Git. I have this in my task file:

```
- name: Copy video packages to server
  synchronize:
    src: "{{ video_files_path }}/{{ item }}"
    dest: "~/{{ item }}"
  with_items: video_packages

- name: Install video packages
  apt: "deb={{ item }} state=present force=yes dpkg_options=force-downgrade"
  with_items: video_packages
```

When I run the task, the synchronize module works fine, but the apt module throws this exception:

```
TASK [timebox : Copy video packages to server] *********************************
ESTABLISH LOCAL CONNECTION FOR USER: deployer
vpn-guardhome1.timeline.is EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135289.56-41204436520860)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135289.56-41204436520860)")
vpn-guardhome1.timeline.is PUT /var/folders/wv/msb2x08n4673j278hhwmlb100000gn/T/tmpO310is TO /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135289.56-41204436520860/synchronize
vpn-guardhome1.timeline.is EXEC /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-apvwijoseuorbqrsyowtouxydelflfui; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135289.56-41204436520860/synchronize; rm -rf "/Users/Hackeron/.ansible/tmp/ansible-tmp-1445135289.56-41204436520860/" > /dev/null 2>&1'"'"''
ESTABLISH LOCAL CONNECTION FOR USER: deployer
vpn-guardhome1.timeline.is EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135291.56-206114014529016)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135291.56-206114014529016)")
vpn-guardhome1.timeline.is PUT /var/folders/wv/msb2x08n4673j278hhwmlb100000gn/T/tmpw_3XLO TO /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135291.56-206114014529016/synchronize
vpn-guardhome1.timeline.is EXEC /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vmcggcfymcblvglfnvqcptcvqubihvlr; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135291.56-206114014529016/synchronize; rm -rf "/Users/Hackeron/.ansible/tmp/ansible-tmp-1445135291.56-206114014529016/" > /dev/null 2>&1'"'"''
ESTABLISH LOCAL CONNECTION FOR USER: deployer
vpn-guardhome1.timeline.is EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135293.54-36647067715605)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135293.54-36647067715605)")
vpn-guardhome1.timeline.is PUT /var/folders/wv/msb2x08n4673j278hhwmlb100000gn/T/tmpPbyixH TO /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135293.54-36647067715605/synchronize
vpn-guardhome1.timeline.is EXEC /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-kjabsjlhnqlokmiutebseeugrqvksybv; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135293.54-36647067715605/synchronize; rm -rf "/Users/Hackeron/.ansible/tmp/ansible-tmp-1445135293.54-36647067715605/" > /dev/null 2>&1'"'"''
ESTABLISH LOCAL CONNECTION FOR USER: deployer
vpn-guardhome1.timeline.is EXEC (umask 22 && mkdir -p "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135295.54-180564548851356)" && echo "$(echo $HOME/.ansible/tmp/ansible-tmp-1445135295.54-180564548851356)")
vpn-guardhome1.timeline.is PUT /var/folders/wv/msb2x08n4673j278hhwmlb100000gn/T/tmpdNmXb2 TO /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135295.54-180564548851356/synchronize
vpn-guardhome1.timeline.is EXEC /bin/sh -c 'sudo -H -n -S -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-icemamwtduhhtbeomtuppmaexljrtgjm; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/Hackeron/.ansible/tmp/ansible-tmp-1445135295.54-180564548851356/synchronize; rm -rf "/Users/Hackeron/.ansible/tmp/ansible-tmp-1445135295.54-180564548851356/" > /dev/null 2>&1'"'"''
ok: [guardhome1] => (item=fdk-aac_latest_amd64.deb) => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/Users/Hackeron/Development/Xanview/xanview-ansible/roles/timebox/files/packages/Ubuntu-15.04/amd64/fdk-aac_latest_amd64.deb\" \"deployer@vpn-guardhome1.timeline.is:~/fdk-aac_latest_amd64.deb\"", "item": "fdk-aac_latest_amd64.deb", "msg": "", "rc": 0, "stdout_lines": []}
ok: [guardhome1] => (item=x264_latest_amd64.deb) => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/Users/Hackeron/Development/Xanview/xanview-ansible/roles/timebox/files/packages/Ubuntu-15.04/amd64/x264_latest_amd64.deb\" \"deployer@vpn-guardhome1.timeline.is:~/x264_latest_amd64.deb\"", "item": "x264_latest_amd64.deb", "msg": "", "rc": 0, "stdout_lines": []}
ok: [guardhome1] => (item=ffmpeg_latest_amd64.deb) => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/Users/Hackeron/Development/Xanview/xanview-ansible/roles/timebox/files/packages/Ubuntu-15.04/amd64/ffmpeg_latest_amd64.deb\" \"deployer@vpn-guardhome1.timeline.is:~/ffmpeg_latest_amd64.deb\"", "item": "ffmpeg_latest_amd64.deb", "msg": "", "rc": 0, "stdout_lines": []}
ok: [guardhome1] => (item=opencv_latest_amd64.deb) => {"changed": false, "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"/Users/Hackeron/Development/Xanview/xanview-ansible/roles/timebox/files/packages/Ubuntu-15.04/amd64/opencv_latest_amd64.deb\" \"deployer@vpn-guardhome1.timeline.is:~/opencv_latest_amd64.deb\"", "item": "opencv_latest_amd64.deb", "msg": "", "rc": 0, "stdout_lines": []}

TASK [timebox : Install video packages] ****************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/process/worker.py", line 117, in run
    executor_result = TaskExecutor(host, task, job_vars, play_context, self._new_stdin, self._loader, shared_loader_obj).run()
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 90, in run
    item_results = self._run_loop(items)
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 201, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 239, in _squash_items
    if templar._contains_vars(name):
  File "/usr/local/Cellar/ansible/HEAD/libexec/lib/python2.7/site-packages/ansible/template/__init__.py", line 339, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [guardhome1]: FAILED! => {"failed": true, "stdout": ""}
```

**Comment by robynbergeron** [comment]
[module: packaging/os/apt.py]

**Comment by robynbergeron** [comment]
Greetings, @hackeron -- thanks for submitting this bug report.

@mgwilliams -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by tetherit** [comment]
If I'm understanding this correctly, it seems support for "apt: deb=package" is missing in last Ansible from git? - Is this something intentional?

**Comment by Gaurav2Github** [comment]
On ansible --version => ansible 2.0.1.0
While using [apt - Manages apt-packages](http://docs.ansible.com/ansible/apt_module.html) to install deb packages.

```
- name: install deb packages
  apt: deb=/tmp/{{item}}
  become: yes
  with_items: 
  - virtualbox-5.0_5.0.14-105127~Ubuntu~trusty_amd64.deb
  - sublime-text_build-3103_amd64.deb
  - vagrant_1.8.1_x86_64.deb
  - google-chrome-stable_current_amd64.deb

```

Getting below error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 92, in run
    item_results = self._run_loop(items)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 223, in _run_loop
    items = self._squash_items(items, task_vars)
  File "/usr/lib/pymodules/python2.7/ansible/executor/task_executor.py", line 273, in _squash_items
    if templar._contains_vars(name):
  File "/usr/lib/pymodules/python2.7/ansible/template/__init__.py", line 373, in _contains_vars
    return self.environment.block_start_string in data or self.environment.variable_start_string in data
TypeError: argument of type 'NoneType' is not iterable

fatal: [gaurav]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

When I install them individually. 

```
- name: install virtualbox deb package
  apt: deb=/tmp/virtualbox-5.0_5.0.14-105127~Ubuntu~trusty_amd64.deb
  become: yes
```

It works fine.

```
TASK [ubuntu-setup : install vagrant deb packages] *****************************
task path: /home/gaurav/devops/ansible-pc-setup/roles/ubuntu-setup/tasks/devtools_install.yml:15
<172.17.157.158> ESTABLISH SSH CONNECTION FOR USER: gaurav
<172.17.157.158> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o 'IdentityFile="roles/ubuntu-setup/files/ubuntu_insecure"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gaurav -o ConnectTimeout=10 -tt 172.17.157.158 '/bin/sh -c '"'"'( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456718404.29-65830451985087 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456718404.29-65830451985087 `" )'"'"''
<172.17.157.158> PUT /tmp/tmpsl7b18 TO /home/gaurav/.ansible/tmp/ansible-tmp-1456718404.29-65830451985087/apt
<172.17.157.158> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o 'IdentityFile="roles/ubuntu-setup/files/ubuntu_insecure"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gaurav -o ConnectTimeout=10 '[172.17.157.158]'
<172.17.157.158> ESTABLISH SSH CONNECTION FOR USER: gaurav
<172.17.157.158> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o Port=22 -o 'IdentityFile="roles/ubuntu-setup/files/ubuntu_insecure"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gaurav -o ConnectTimeout=10 -tt 172.17.157.158 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=qtwryvslyxloapyptzauggtzphunrrgg] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qtwryvslyxloapyptzauggtzphunrrgg; /bin/sh -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'LANG=en_NZ.UTF-8 LC_ALL=en_NZ.UTF-8 LC_MESSAGES=en_NZ.UTF-8 /usr/bin/python /home/gaurav/.ansible/tmp/ansible-tmp-1456718404.29-65830451985087/apt; rm -rf "/home/gaurav/.ansible/tmp/ansible-tmp-1456718404.29-65830451985087/" > /dev/null 2>&1'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"''"'"''
ok: [gaurav] => {"changed": false, "invocation": {"module_args": {"cache_valid_time": null, "deb": "/tmp/vagrant_1.8.1_x86_64.deb", "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "package": null, "purge": false, "state": "present", "update_cache": false, "upgrade": null}, "module_name": "apt"}, "stderr": "", "stdout": "", "stdout_lines": []}

```

Issue seems to be in iteration of items while installing deb packages.

After looking into the code, the module seems to accept only one deb file at a time.
and fails if list is passed.

Is this being updated any time soon?

**Comment by bbatsche** [comment]
@Gaurav2Github: I'm having the same issue. I think this is a recent bug with Ansible 2.0.1.0, so I've opened a new ticket for it: #3145

**Comment by gdevenyi** [comment]
2.0.1 still has this bug, it was not closed by https://github.com/ansible/ansible/issues/14709

**Comment by egroeper** [comment]
@gdevenyi It seems to me, that no released version contains the fix.
At least  `git tag --contains 67d5b77898872335f18fd58f3aa53798ef7a2e31` doesn't yield any tag.
I can confirm, that on current devel branch the issue doesn't exist anymore.

**Comment by stefanocrosta** [comment]
Confirm that as of today, no pip installable version has the fix. Please push a new version!
Having to use the dev branch breaks our standard workflow... thanks!

**Comment by jeroenjacobs79** [comment]
@stefanocrosta 

An easy workaround is to use "pkg" instead of "package" in your Ansible config. Instead of:

```
apt: package={{ item }} state=latest
```

use:

```
apt: pkg={{ item }} state=latest
```

**Comment by tetherit** [comment]
@jeroenjacobs1205 the bug report is for installing deb files, e.g. "apt: deb=/tmp/something.deb" so the workaround doesn't apply.

**Comment by abadger** [comment]
I just tested this with 2.0.2.0 and it seems to be working fine:

```
---
- hosts: 192.168.122.13
  tasks:
  - apt:
      deb: "{{item}}"
      state: present
    with_items:
      - /home/badger/tmux_1.8-5_amd64.deb
      - /home/badger/byobu_5.77-0ubuntu1.2_all.deb
```

```
$ ansible-playbook 2300.yml -i '192.168.122.13,' --sudo -K       (11:25:01)
SUDO password: 

PLAY [192.168.122.13] **********************************************************

TASK [setup] *******************************************************************
ok: [192.168.122.13]

TASK [apt] *********************************************************************
changed: [192.168.122.13] => (item=/home/badger/tmux_1.8-5_amd64.deb)
changed: [192.168.122.13] => (item=/home/badger/byobu_5.77-0ubuntu1.2_all.deb)

PLAY RECAP *********************************************************************
192.168.122.13             : ok=2    changed=1    unreachable=0    failed=0
```

I ran into an unrelated error when trying this on devel.  I'll research that separately.

**Comment by egroeper** [comment]
@abadger I can confirm it works with 2.0.2.0 here.
