### ISSUE TITLE
module ec2_asg fails when existing ASG has tags

### ISSUE THREAD

**Issue by robbwagoner** [ansible/ansible-modules-core#274]
This error went away once I removed all tags from the ASG.

``````
TASK: [autoscaling | Auto Scaling Group] ************************************** 
<localhost> REMOTE_MODULE ec2_asg max_size=1 launch_config_name='staging sclr/release-v0.7.1 irx_api/v0.99.8 ansible-irx/40cad98' health_check_type=ELB state=present desired_capacity=1 min_size=1 region=us-east-1 name=continuous-integration-staging
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1415162454.65-183842690328511/ec2_asg", line 2324, in <module>
    main()
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1415162454.65-183842690328511/ec2_asg", line 2322, in main
    module.exit_json( changed = changed, **asg_properties )
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1415162454.65-183842690328511/ec2_asg", line 1388, in exit_json
    print self.jsonify(kwargs)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1415162454.65-183842690328511/ec2_asg", line 1366, in jsonify
    return json.dumps(data)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Tag(irx_api_sha=7093504) is not JSON serializable```
``````

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
