### ISSUE TITLE
elasticsearch: An exception occurred during task execution.

### ISSUE THREAD

**Issue by dnegreira** [ansible/ansible-modules-core#2755]
# Issue type: Bug Report
# Summary:

When I use the AWS elasticache module with the latest development branch from Ansible, it throws an exception as per below. I am not sure when it was working before as I am using this for the first time.
Environment: Ubuntu 15.10.
# Ansible Version:

```
straight from git:
ansible --version 
ansible 2.1.0 (devel 210cf06d9a) last updated 2016/01/04 14:58:17 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 002028748f) last updated 2016/01/04 14:59:10 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f6a7b6dd1f) last updated 2016/01/04 14:59:23 (GMT +200)
  config file = /home/dnegreira/git/ansible/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
# Steps to reproduce:

```
Playbook:
setup-aws.yml
- name: Setup AWS infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
   - aws-elasticache
```

```
role:
roles/aws-elasticache/tasks/main.yml
- name: "Create elasticache instances"
  elasticache:
    name: "test"
    state: present
    engine: "redis"
    cache_subnet_group: "test"
    cache_engine_version: "2.8.23"
    node_type: "cache.t2.micro"
    num_nodes: "1"
    cache_port: 6379
    region: "eu-central-1"
    zone: "eu-central-1b"
```

`$ ansible-playbook -vvv setup-aws.yml -i inventory/`
# Error:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 2770, in <module>
    main()
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 562, in main
    module.exit_json(**facts_result)
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 2134, in exit_json
    kwargs = remove_values(kwargs, self.no_log_values)
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in remove_values
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 982, in <genexpr>
    return dict((k, remove_values(v, no_log_strings)) for k, v in value.items())
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 980, in remove_values
    return [remove_values(elem, no_log_strings) for elem in value]
  File "/home/dnegreira/.ansible/tmp/ansible-tmp-1451916696.76-192287950097298/elasticache", line 991, in remove_values
    raise TypeError('Value of unknown type: %s, %s' % (type(value), value))
TypeError: Value of unknown type: <type 'object'>, <object object at 0x7fe1d58520f0>

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "elasticache"}, "parsed": false}
```

**Comment by domkck** [comment]
:+1: having exactly the same issue. Tasks that trigger the issue (Ansible version `2.0.0.2` from pip):

```
tasks:
    - name: Create a subnet group for caches
      elasticache_subnet_group:
        state: present
        name: "{{ subnet_group_name }}"
        description: "Redis eu-west-1 subnet group {{ environment }}"
        subnets: "{{ subnets | map(attribute='subnet_id') | list }}"
        region: eu-west-1
    - name: "Create the Redis instance for {{ item.instance_name }}"
      elasticache:
        name: "{{ item.instance_name }}-{{environment}}"
        state: present
        engine: redis
        node_type: "{{ item.instance_type }}"
        num_nodes: "{{ item.num_nodes }}"
        region: eu-west-1
        zone: eu-west-1a
        cache_subnet_group: "{{ subnet_group_name }}"
        wait: yes
```

**Comment by noqcks** [comment]
This pull request should fix the issue https://github.com/ansible/ansible-modules-core/pull/2735 It's very close to being pulled in. 

Unfortunately, I think it has been this way for a while.

**Comment by jimi-c** [comment]
I've just merged the above commit into devel, so closing this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by dnegreira** [comment]
@noqcks Thanks for the fix!
