### ISSUE TITLE
ec2_elb_lb stickiness option does not work

### ISSUE THREAD

**Issue by tomfotherby** [ansible/ansible-modules-core#2861]
##### Issue Type:

 Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

```
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```
##### Summary:

When the new `stickiness` option is used, I get a error (except for the first time it's run)
##### Steps To Reproduce:

This playbook fails, but if I run it without the `stickiness` options, it succeeds:

```

---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Update the stickiness of ELBs that need it enabled
      ec2_elb_lb:
        name: "tf-lb-3usudlb7prhf5c6vdfy2rb74w4"
        state: present
        aws_access_key: "redacted"
        aws_secret_key: "redacted"
        region: "us-east-1"
        zones:
          - us-east-1a
          - us-east-1b
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_protocol: http
            instance_port: 14705
        purge_listeners: no
        stickiness:
            type: loadbalancer
            enabled: yes
            expiration: 0
```
##### Expected Results:

Should succeed and should set stickiness on.
##### Actual Results:

Works first time, then get error:

```
  <Error>
    <Type>Sender</Type>
    <Code>LoadBalancerNotFound</Code>
    <Message>Cannot find Load Balancer t</Message>
  </Error>
```

In full:

```
TASK [Update the stickiness of ELBs that need it enabled] **********************
task path: /var/lib/awx/projects/redacted/elb_stickiness_single.yml:6
ESTABLISH LOCAL CONNECTION FOR USER: awx
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119 )" )
127.0.0.1 PUT /tmp/tmpmjK3rs TO /var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb
127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/" > /dev/null 2>&1
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb", line 3148, in <module>
    main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb", line 974, in main
    elb_man.ensure_ok()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb", line 379, in ensure_ok
    self.select_stickiness_policy()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1453485370.37-244154666852119/ec2_elb_lb", line 807, in select_stickiness_policy
    elb_info = self.elb_conn.get_all_load_balancers(self.elb.name)[0]
  File "/usr/lib/python2.7/dist-packages/boto/ec2/elb/__init__.py", line 139, in get_all_load_balancers
    [('member', LoadBalancer)])
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1127, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>LoadBalancerNotFound</Code>
    <Message>Cannot find Load Balancer t</Message>
  </Error>
  <RequestId>6b9c1f73-c131-11e5-bc27-cd7c7e961f31</RequestId>
</ErrorResponse>


fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_elb_lb"}, "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```

**Comment by tomfotherby** [comment]
My problem went away when I upgraded boto with `sudo pip install boto --upgrade`

Previously I was on `2.20.1` and after the upgrade I was on `2.39.0`

```
$ sudo pip install boto --upgrade
Downloading/unpacking boto from https://pypi.python.org/packages/2.7/b/boto/boto-2.39.0-py2.py3-none-any.whl#md5=7a3905b33f003950e16e19b1f8ee8725
  Downloading boto-2.39.0-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: boto
  Found existing installation: boto 2.20.1
    Uninstalling boto:
      Successfully uninstalled boto
Successfully installed boto
Cleaning up...
```
