### ISSUE TITLE
ec2_metric_alarm seems to require dimensions

### ISSUE THREAD

**Issue by cwalkatron** [ansible/ansible-modules-core#3023]
The `dimensions` argument to `ec2_metric_alarm`, according to the documentation, is not required. I am using a custom namespace with no dimension. If I leave out dimension, I get the following when running a playbook:

```
TASK: [autoscale | create queue too deep alarm] *******************************
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/cwalker/.ansible/tmp/ansible-tmp-1455231479.92-237430965834311/ec2_metric_alarm", line 2093, in <module>
    main()
  File "/home/cwalker/.ansible/tmp/ansible-tmp-1455231479.92-237430965834311/ec2_metric_alarm", line 2089, in main
    create_metric_alarm(connection, module)
  File "/home/cwalker/.ansible/tmp/ansible-tmp-1455231479.92-237430965834311/ec2_metric_alarm", line 2001, in create_metric_alarm
    for keys in dim1:
TypeError: 'NoneType' object is not iterable


FATAL: all hosts have already failed -- aborting
```

You can make the API call another way and dimensions is not required.

**Comment by cwalkatron** [comment]
This is because I hadn't specified `period`.
