### ISSUE TITLE
nxos_config doesn't iterate through parents

### ISSUE THREAD

**Issue by RNanney** [ansible/ansible-modules-core#3274]
##### Issue Type:

- Bug Report
##### Plugin Name:

nxos_config
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = /home/bob/ansible-networking/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

inventory      = ~/ansible-networking/inventory/
ask_sudo_pass = False
ask_pass      = False
gathering = explicit
##### Environment:

N/A
##### Summary:

Error when parents has multiple values
##### Steps To Reproduce:

give the parents paremeter multiple values

https://gist.github.com/RNanney/d7010f3792ccfb3b54ae
##### Expected Results:

I expect ansible to go in to the configuration mode for each parent
##### Actual Results:

I get a traceback

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/bob/.ansible/tmp/ansible-tmp-1458314657.46-98670675144040/nxos_config", line 3629, in <module>
    main()
  File "/home/bob/.ansible/tmp/ansible-tmp-1458314657.46-98670675144040/nxos_config", line 229, in main
    for item in config:
TypeError: 'ConfigLine' object is not iterable

fatal: [10.127.49.32]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_config"}, "parsed": false}
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/bob/.ansible/tmp/ansible-tmp-1458314657.45-198974342277944/nxos_config", line 3629, in <module>
    main()
  File "/home/bob/.ansible/tmp/ansible-tmp-1458314657.45-198974342277944/nxos_config", line 229, in main
    for item in config:
TypeError: 'ConfigLine' object is not iterable

fatal: [10.127.49.31]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_config"}, "parsed": false}
```

**Comment by privateip** [comment]
should be fixed now.  also just a quick comment, you do not have to sequentially build the hierarchy in the config.   

```
nxos_config:
  lines:
    - foo
  parents:
    - bar
    - baz
```

In the above example, if bar isn't already in the config, the module will construct:

```
bar
  baz
    foo
```
