### ISSUE TITLE
Unable to install Python 3.5 packages using the pip module

### ISSUE THREAD

**Issue by fgimian** [ansible/ansible-modules-core#3298]
##### Issue Type:
- Bug Report
##### Plugin Name:

packaging/language/pip
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

No ansible.cfg present
##### Environment:

Mac OS X 10.11.3 (15D21)
##### Summary:

Unable to install packages using the pip module when executable is Python 3.x pip
##### Steps To Reproduce:

Firstly, you can see that pip3 works correctly when run without Ansible:

```
Fotsies-MBP:macbuild fots$ pip3 install ipython
Collecting ipython
  Downloading ipython-4.1.2-py3-none-any.whl (736kB)
    100% |████████████████████████████████| 737kB 333kB/s 
Requirement already satisfied (use --upgrade to upgrade): appnope in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): gnureadline in /usr/local/lib/python3.5/site-packages (from ipython)
Requirement already satisfied (use --upgrade to upgrade): path.py>=6.2 in /usr/local/lib/python3.5/site-packages (from pickleshare->ipython)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python3.5/site-packages (from pexpect->ipython)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python3.5/site-packages (from traitlets->ipython)
Installing collected packages: ipython
Successfully installed ipython-4.1.2
You are using pip version 8.0.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

However, when trying this with Ansible, we get an exception:

```
otsies-MBP:macbuild fots$ ansible localhost -m pip -a "name=ipython state=latest executable=pip3"
localhost | FAILED! => {
    "changed": false, 
    "cmd": "/usr/local/bin/pip3 install -U ipython", 
    "failed": true, 
    "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/pip3\", line 9, in <module>\n    load_entry_point('pip==8.0.2', 'console_scripts', 'pip3')()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 549, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2542, in load_entry_point\n    return ep.load()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2202, in load\n    return self.resolve()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2208, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n  File \"/usr/local/lib/python3.5/site-packages/pip/__init__.py\", line 15, in <module>\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/local/lib/python3.5/site-packages/pip/vcs/subversion.py\", line 9, in <module>\n    from pip.index import Link\n  File \"/usr/local/lib/python3.5/site-packages/pip/index.py\", line 29, in <module>\n    from pip.wheel import Wheel, wheel_ext\n  File \"/usr/local/lib/python3.5/site-packages/pip/wheel.py\", line 6, in <module>\n    import compileall\n  File \"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/compileall.py\", line 20, in <module>\n    from concurrent.futures import ProcessPoolExecutor\n  File \"/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/__init__.py\", line 8, in <module>\n    from concurrent.futures._base import (FIRST_COMPLETED,\n  File \"/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/_base.py\", line 357\n    raise type(self._exception), self._exception, self._traceback\n                               ^\nSyntaxError: invalid syntax\n"
}
```
##### Expected Results:

Expected ipython to be installed in my Python 3.x environment
##### Actual Results:

```
Fotsies-MBP:macbuild fots$ ansible -vvvv localhost -m pip -a "name=ipython state=latest executable=pip3"
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
ESTABLISH LOCAL CONNECTION FOR USER: fots
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1458616109.17-280776356178950 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1458616109.17-280776356178950 `" )'
127.0.0.1 PUT /var/folders/rf/z0ksnk7d4031bmw8zg8gh5f00000gn/T/tmphAAvMP TO /Volumes/Data/fots/.ansible/tmp/ansible-tmp-1458616109.17-280776356178950/pip
127.0.0.1 EXEC /bin/sh -c 'LANG=en_AU.UTF-8 LC_ALL=en_AU.UTF-8 LC_MESSAGES=en_AU.UTF-8 /usr/bin/python /Volumes/Data/fots/.ansible/tmp/ansible-tmp-1458616109.17-280776356178950/pip; rm -rf "/Volumes/Data/fots/.ansible/tmp/ansible-tmp-1458616109.17-280776356178950/" > /dev/null 2>&1'
localhost | FAILED! => {
    "changed": false, 
    "cmd": "/usr/local/bin/pip3 install -U ipython", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "chdir": null, 
            "editable": true, 
            "executable": "pip3", 
            "extra_args": null, 
            "name": "ipython", 
            "requirements": null, 
            "state": "latest", 
            "use_mirrors": true, 
            "version": null, 
            "virtualenv": null, 
            "virtualenv_command": "virtualenv", 
            "virtualenv_python": null, 
            "virtualenv_site_packages": false
        }, 
        "module_name": "pip"
    }, 
    "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/local/bin/pip3\", line 9, in <module>\n    load_entry_point('pip==8.0.2', 'console_scripts', 'pip3')()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 549, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2542, in load_entry_point\n    return ep.load()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2202, in load\n    return self.resolve()\n  File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 2208, in resolve\n    module = __import__(self.module_name, fromlist=['__name__'], level=0)\n  File \"/usr/local/lib/python3.5/site-packages/pip/__init__.py\", line 15, in <module>\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/local/lib/python3.5/site-packages/pip/vcs/subversion.py\", line 9, in <module>\n    from pip.index import Link\n  File \"/usr/local/lib/python3.5/site-packages/pip/index.py\", line 29, in <module>\n    from pip.wheel import Wheel, wheel_ext\n  File \"/usr/local/lib/python3.5/site-packages/pip/wheel.py\", line 6, in <module>\n    import compileall\n  File \"/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/compileall.py\", line 20, in <module>\n    from concurrent.futures import ProcessPoolExecutor\n  File \"/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/__init__.py\", line 8, in <module>\n    from concurrent.futures._base import (FIRST_COMPLETED,\n  File \"/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/_base.py\", line 357\n    raise type(self._exception), self._exception, self._traceback\n                               ^\nSyntaxError: invalid syntax\n"
}
```

**Comment by fgimian** [comment]
Here's the exception formatted correctly for you :smile: 

```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==8.0.2', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.5/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/local/lib/python3.5/site-packages/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 6, in <module>
    import compileall
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/local/Cellar/ansible/2.0.1.0/libexec/vendor/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
                               SyntaxError: invalid syntax
```

**Comment by fgimian** [comment]
This appears to be specific to the Homebrew version of Ansible.  Further information to follow, perhaps this needs to be raised against Homebrew instead :smile:

**Comment by guhcampos** [comment]
+1 I get the exact same error while trying to use Ansible from Homebrew and Python 3.5.1. 

Ansible is installed into Python2.7 site-packages by brew, but it turns out it's impossible to manage a Python 3.5 virtual env from it. 

I got the same error on a remote Python 3.5 install as well, as opposed to `localhost`

**Comment by sivel** [comment]
Just of note here, homebrew is not an officially supported method of installing Ansible.  The recommended method of installing Ansible on Mac is via pip.

Due to this I am inclined to close this as the issue is specific to homebrew installed Ansible.

**Comment by fgimian** [comment]
I understand @sivel, I'll close this for you and raise it against the Homebrew guys :smile: 

Thanks for your reply
Fotis

**Comment by RyoIto** [comment]
https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/disconnections-explained
