### ISSUE TITLE
intermittent failure when running local with multiple target nodes

### ISSUE THREAD

**Issue by aermongk** [ansible/ansible-modules-core#3504]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

See traceback below.

ansible/executor/module_common.py ???
file.py- mkdir ???
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = /home/ansible/local/library:/home/ansible/ansible/lib/ansible/modules/core/network/iosxr
```
##### CONFIGURATION

No configuration changed.
##### OS / ENVIRONMENT

Linux dev-box 4.2.0-25-generic #30-Ubuntu SMP Mon Jan 18 12:31:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

Using iosxr network module, I ran into a race condition similar to #1649.  I ran playbook in local mode with multiple IOS-XR target nodes, race condition occurred trying to create temp directory ziploader_cache on the local server.  I do have #1649 fix in my ansible core module.
##### STEPS TO REPRODUCE

I created a simple iosxr network module called "get_config" with the following code.  Occasionally, I see the "OSError: [Error 17] File exists: ..." failure when running playbook.

```
module = get_module(
    argument_spec = dict(
        username = dict(required=True),
        password = dict(required=True),
    ),
    supports_check_mode = True
)
result = dict(changed=False)
result['stdout'] = module.get_config()
return module.exit_json(**result)
```

And run this simple playbook several times.

```
- hosts: ss-xr
  connection: local
  gather_facts: no

  tasks:
  - get_config:
      host: '{{ ansible_host }}'
      username: 'root'
      password: 'root'
    register: output
  - debug: var=output
```

##### EXPECTED RESULTS

PLAY RECAP *********************************************************************
192.168.1.10               : ok=2    changed=0    unreachable=0    failed=0  
192.168.1.12               : ok=2    changed=0    unreachable=0    failed=0 
##### ACTUAL RESULTS

PLAY RECAP *********************************************************************
192.168.1.10               : ok=2    changed=0    unreachable=0    failed=0  
192.168.1.12               : ok=0    changed=0    unreachable=0    failed=1   

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/executor/task_executor.py", line 426, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/__init__.py", line 517, in _execute_module
    (module_style, shebang, module_data) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/plugins/action/__init__.py", line 147, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/executor/module_common.py", line 533, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/local/lib/python2.7/dist-packages/ansible-2.1.0-py2.7.egg/ansible/executor/module_common.py", line 389, in _find_snippet_imports
    os.mkdir(lookup_path)
OSError: [Errno 17] File exists: '/home/ansible/.ansible/tmp/ansible-local-tmpRplCmb/ziploader_cache'

fatal: [192.168.1.12]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```

**Comment by abadger** [comment]
Since 2.1.0 has not yet been released, your ansible --version output should include the git hash for your ansible checkout.  Since it's not there, I can't tell whether you have the latest version of ansible or not.  I think you might have a slightly older checkout because this could be this fix from a few days ago:

```
commit d2a7be142e1436981f985ab896d603e8a9396a0d
Author: Toshio Kuratomi <toshio@fedoraproject.org>
Date:   Mon Apr 18 11:51:45 2016 -0700

    A couple fixes for ziploader:

    * Move zipcache temp dir creation into the locked section otherwise it
      races with other workers.
    * Catch IOError and turn it into an AnsibleError.  IOErrors can hang
      multiprocessng.
```

Try updating and seeing if that solves the problem for you.

**Comment by aermongk** [comment]
That seemed to fix the problem. Thanks Toshio.

**Comment by ghost** [comment]
This is back - in 2.1.0 release version:

```
RUNNING HANDLER [cassandra-collection : Stop cassandra] ************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/home/ansible/.ansible/tmp/ansible-local-tmpWcdyys/ziploader_cache'
fatal: [REDACTED]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

That 'Stop cassandra' is:

```
- name: Stop cassandra
  service: name=cassandra state=stopped
```

Kernel 3.19.0-61-generic #69~14.04.1-Ubuntu
ansible 2.1.0.0
