### ISSUE TITLE
user module on darwin failing

### ISSUE THREAD

**Issue by juju4** [ansible/ansible-modules-core#3506]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

user
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.2.0
  config file = /opt/tmp/vagrant/homelab/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Orchestrator: Ubuntu trusty
Target: OSX 10.10
##### SUMMARY

Trying to add a user on Darwin side and failing

```
TASK [adduser : Add user] ******************************************************
task path: /path/to/roles/adduser/tasks/main.yml:3
<192.168.x.y> ESTABLISH SSH CONNECTION FOR USER: admin
<192.168.x.y> SSH: EXEC sshpass -d13 ssh -C -q -o ForwardAgent=yes -o User=admin -o ConnectTimeout=10 192.168.x.y '/bin/sh -c '"'"'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python'"'"''
fatal: [HOST]: FAILED! => {"changed": false, "err": "", "failed": true, "invocation": {"module_args": {"append": false, "comment": "orchestration user", "createhome": true, "expires": null, "force": false, "generate_ssh_key": null, "group": null, "groups": null, "home": null, "login_class": null, "move_home": false, "name": "deploy", "non_unique": false, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "remove": false, "shell": "/bin/bash", "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on MacBook-Pro.local", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": false, "uid": null, "update_password": "always"}, "module_name": "user"}, "msg": "Cannot create user \"deploy\".", "out": "<main> attribute status: eDSPermissionError\n<dscl_cmd> DS Error: -14120 (eDSPermissionError)\n", "rc": 40}
```

Used https://github.com/juju4/ansible-adduser
tried with or without password or comment fields for adduser module
##### STEPS TO REPRODUCE

```
- hosts: test
  roles:
    - adduser
```

```
$ ansible-playbook -i inventory --limit macbook site.yml -u admin --ask-pass --ask-sudo-pass -vvv
```
##### EXPECTED RESULTS

user is added
##### ACTUAL RESULTS

ping and setup are fine.

```
TASK [adduser : Add user] ******************************************************
task path: /path/to/roles/adduser/tasks/main.yml:3
<192.168.x.y> ESTABLISH SSH CONNECTION FOR USER: admin
<192.168.x.y> SSH: EXEC sshpass -d13 ssh -C -q -o ForwardAgent=yes -o User=admin -o ConnectTimeout=10 192.168.x.y '/bin/sh -c '"'"'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python'"'"''
fatal: [HOST]: FAILED! => {"changed": false, "err": "", "failed": true, "invocation": {"module_args": {"append": false, "comment": "orchestration user", "createhome": true, "expires": null, "force": false, "generate_ssh_key": null, "group": null, "groups": null, "home": null, "login_class": null, "move_home": false, "name": "deploy", "non_unique": false, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "remove": false, "shell": "/bin/bash", "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on MacBook-Pro.local", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": false, "uid": null, "update_password": "always"}, "module_name": "user"}, "msg": "Cannot create user \"deploy\".", "out": "<main> attribute status: eDSPermissionError\n<dscl_cmd> DS Error: -14120 (eDSPermissionError)\n", "rc": 40}
```

I have the same error when running from target terminal without sudo (but was asked too both in cli or inventory

```
$ dscl . -create /Users/deploy
```

the following command is fine (no error returned but...)

```
$ sudo dscl . -create /Users/deploy
```

If I reexecute playbook after

```
fatal: [HOST]: FAILED! => {"changed": false, "err": "", "failed": true, "invocation": {"module_args": {"append": false, "comment": "orchestration user", "createhome": true, "expires": null, "force": false, "generate_ssh_key": null, "group": null, "groups": null, "home": null, "login_class": null, "move_home": false, "name": "deploy", "non_unique": false, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "remove": false, "shell": "/bin/bash", "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on MacBook-Pro.local", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": false, "uid": null, "update_password": "always"}, "module_name": "user"}, "msg": "Cannot update property \"comment\" for user \"deploy\".", "out": "", "rc": 40}
```

seems a sudo/become issue.
But even if I comment the task, the rest of playbook fails

I can list user but can't su/sudo to it...

```
$ dscl . -create /Users/deploy
$ dscl . list /Users/deploy
$
$ sudo -u deploy -s
sudo: unknown user: deploy
$ sudo su - deploy
su: unknown login: deploy
$ dscl . list /Users | grep deploy
deploy
```

and found few doc on it
http://www.techradar.com/us/how-to/computing/apple/terminal-101-creating-new-users-1305687
http://www.greenend.org.uk/rjk/tech/useradd.html

Note: a user hidden option would be useful
https://support.apple.com/en-us/HT203998

**Comment by juju4** [comment]
For reference, with user working, next step of playbook fails again on permission

```
TASK [adduser : Add authorized keys for deploy user] ***************************
task path: /path/to/roles/adduser/tasks/main.yml:11
<192.168.x.y> ESTABLISH SSH CONNECTION FOR USER: admin
<192.168.x.y> SSH: EXEC sshpass -d13 ssh -C -q -o ForwardAgent=yes -o User=admin -o ConnectTimeout=10 192.168.x.y '/bin/sh -c '"'"'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python'"'"''
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 3313, in <module>
  File "<stdin>", line 466, in main
  File "<stdin>", line 442, in enforce_state
  File "<stdin>", line 202, in keyfile
OSError: [Errno 1] Operation not permitted: '/Users/deploy/.ssh'

failed: [HOST] (item=ssh-rsa AAAAKEY user@) => {"failed": true, "invocation": {"module_name": "authorized_key"}, "item": "ssh-rsa AAAAKEY user@", "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 3313, in <module>\n  File \"<stdin>\", line 466, in main\n  File \"<stdin>\", line 442, in enforce_state\n  File \"<stdin>\", line 202, in keyfile\nOSError: [Errno 1] Operation not permitted: '/Users/deploy/.ssh'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

```

(.ssh dir exists)

**Comment by juju4** [comment]
Sorry, fix it with become: yes for task/role
what is strange is this was necessary to be this with my linux host.
