### ISSUE TITLE
Unable to update existing vlans using junos_template and action:replace

### ISSUE THREAD

**Issue by rhicks** [ansible/ansible-modules-core#4059]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

modules/core/network/junos/junos_template.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat /etc/ansible/ansible.cfg | grep -v "#"
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
control_path = %(directory)s/ansible-ssh-%%C
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT

```
Linux: 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Juniper Model: qfx10002-36q
Junos: 15.1X53-D32.2
```
##### SUMMARY

Unable to push vlan changes via the junos_template.
##### STEPS TO REPRODUCE

Create new vlans on the Juniper device.
Need to update vlan names.
Try to use the "action: replace" option to replace the existing vlans with new names.
Ansible fails with a CommitError stating the vlan-id already exists.

```
- name: template vlan configuration
  junos_template:
    src: vlans.conf.j2
    action: replace
    config_format: text
```

##### EXPECTED RESULTS

Using the "action: replace" option, I would expect the ability to replace existing vlans.
##### ACTUAL RESULTS

"action: replace" seems to act the same as "action: merge".  Both run a commit check and fail if the vlan-id already exists.

```
TASK [juniper : template vlan configuration] ***********************************
task path: /home/rhicks/Repo/systems/playbooks/roles/juniper/tasks/configuration.yml:46
<207.98.65.52> ESTABLISH LOCAL CONNECTION FOR USER: rhicks
<207.98.65.52> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467130505.36-235416664179141 `" && echo ansible-tmp-1467130505.36-235416664179141="` echo $HOME/.ansible/tmp/ansible-tmp-1467130505.36-235416664179141 `" ) && sleep 0'
<207.98.65.52> PUT /tmp/tmpzZj3Ew TO /home/rhicks/.ansible/tmp/ansible-tmp-1467130505.36-235416664179141/junos_template
<207.98.65.52> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/rhicks/.ansible/tmp/ansible-tmp-1467130505.36-235416664179141/junos_template; rm -rf "/home/rhicks/.ansible/tmp/ansible-tmp-1467130505.36-235416664179141/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Top6nu/ansible_module_junos_template.py", line 151, in <module>
    main()
  File "/tmp/ansible_Top6nu/ansible_module_junos_template.py", line 138, in main
    format=fmt, commit=commit, confirm=confirm)
  File "/tmp/ansible_Top6nu/ansible_modlib.zip/ansible/module_utils/junos.py", line 311, in load_config
  File "/tmp/ansible_Top6nu/ansible_modlib.zip/ansible/module_utils/junos.py", line 223, in load_config
  File "/tmp/ansible_Top6nu/ansible_modlib.zip/ansible/module_utils/junos.py", line 194, in check_config
  File "/usr/lib/python2.7/site-packages/jnpr/junos/utils/config.py", line 168, in commit_check
    raise CommitError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.CommitError: CommitError(edit_path: [edit vlans], bad_element: nero-cps-losa_1, message: error: l2ald: Duplicate vlan-id exists for vlan nero-cps-losa
error: Failed to parse vlan hierarchy completely
error: configuration check-out failed)

fatal: [ogig-fabric1-sw.nero.net]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"action": "replace", "comment": "template vlan configuration", "config_format": "text", "host": "<REMOVED>", "password": "<REMOVED>", "src": "vlans {\n  cps-peering {\n    description \"Internet2 Commercial Peering Service\";\n    vlan-id 164;\n  }\n  re-peering {\n    description \"Internet2 Research and Education Peering\";\n    vlan-id 537;\n  }\n  nero-re-losa_1 {\n    description \"R&E - NERO to LOSA #1\";\n    vlan-id 1401;\n  }\n  nero-re-seat_1 {\n    description \"R&E - NERO to SEAT #1\";\n    vlan-id 1421}
    to retry, use: --limit @playbooks/junos-test.retry

PLAY RECAP *********************************************************************
ogig-fabric1-sw.nero.net   : ok=0    changed=0    unreachable=0    failed=1  
```

**Comment by rhicks** [comment]
This is resolved by deleting the vlans in the template before trying to update them.
Any changes will be honored.  Unchanged items will remain unchanged and ignored by the commit.

Issues described here:
https://github.com/Juniper/ansible-junos-stdlib/issues/65

Keyword is "delete: vlan;"

Example:

```
interfaces {
    ge-0/0/7 {
        description TEST;
        unit 0 {
            family ethernet-switching {
                port-mode access;
                delete: vlan; 
                vlan {
                    members VL0002;
                }
            }
        }
    }
}
```
