### ISSUE TITLE
docker_image ends with exception in docker-py dependency

### ISSUE THREAD

**Issue by dgjnpr** [ansible/ansible-modules-core#4116]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker/docker_image
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No configuration modifications have been made.
##### OS / ENVIRONMENT

Running OS X 10.11.5 using Docker beta 1.12.0-rc3-beta18 (build: 9996)
##### SUMMARY

docker_image is able to build a container locally, however it raises a ValueError and so does not exit gracefully.

This error does not appear to be related to other docker_image issue reports that are still open.
##### STEPS TO REPRODUCE

This is the Dockerfile being used

```
FROM jenkins:1.651.3

COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
# ENTRYPOINT /bin/bash

ENV JENKINS_OPTS --httpPort=8080
EXPOSE 8080
```

This is the playbook

```
- name: Begin CI setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Build Jenkins
      docker_image:
        name: my_jenkins
        path: .
        state: present
        tag: "0.0.2"
```

This is the contents of plugins.txt

```
ansible:0.5
authorize-project:1.2.2
robot:1.6.4
```
##### EXPECTED RESULTS

That the playbook completes with raising an exception
##### ACTUAL RESULTS

```
$ ansible-playbook ci-setup.yaml -vvvv
No config file found; using defaults
 [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: ci-setup.yaml ********************************************************
1 plays in ci-setup.yaml

PLAY [Begin CI setup] **********************************************************

TASK [Build Jenkins] ***********************************************************
task path: /Users/dgethings/git/nita-docker/ci-setup.yaml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dgethings
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1467824137.78-138150749658968 `" && echo ansible-tmp-1467824137.78-138150749658968="` echo $HOME/.ansible/tmp/ansible-tmp-1467824137.78-138150749658968 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpb5vYRD TO /Users/dgethings/.ansible/tmp/ansible-tmp-1467824137.78-138150749658968/docker_image
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/dgethings/.ansible/tmp/ansible-tmp-1467824137.78-138150749658968/docker_image; rm -rf "/Users/dgethings/.ansible/tmp/ansible-tmp-1467824137.78-138150749658968/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xmAJFg/ansible_module_docker_image.py", line 531, in <module>
    main()
  File "/tmp/ansible_xmAJFg/ansible_module_docker_image.py", line 523, in main
    ImageManager(client, results)
  File "/tmp/ansible_xmAJFg/ansible_module_docker_image.py", line 243, in __init__
    self.present()
  File "/tmp/ansible_xmAJFg/ansible_module_docker_image.py", line 272, in present
    self.results['image'] = self.build_image()
  File "/tmp/ansible_xmAJFg/ansible_module_docker_image.py", line 457, in build_image
    for line in self.client.build(**params):
  File "/Library/Python/2.7/site-packages/docker/client.py", line 233, in _stream_helper
    data = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 58 - 152)

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "docker_image"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xmAJFg/ansible_module_docker_image.py\", line 531, in <module>\n    main()\n  File \"/tmp/ansible_xmAJFg/ansible_module_docker_image.py\", line 523, in main\n    ImageManager(client, results)\n  File \"/tmp/ansible_xmAJFg/ansible_module_docker_image.py\", line 243, in __init__\n    self.present()\n  File \"/tmp/ansible_xmAJFg/ansible_module_docker_image.py\", line 272, in present\n    self.results['image'] = self.build_image()\n  File \"/tmp/ansible_xmAJFg/ansible_module_docker_image.py\", line 457, in build_image\n    for line in self.client.build(**params):\n  File \"/Library/Python/2.7/site-packages/docker/client.py\", line 233, in _stream_helper\n    data = json.loads(data)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py\", line 338, in loads\n    return _default_decoder.decode(s)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py\", line 369, in decode\n    raise ValueError(errmsg(\"Extra data\", s, end, len(s)))\nValueError: Extra data: line 2 column 1 - line 3 column 1 (char 58 - 152)\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
  to retry, use: --limit @ci-setup.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

$ docker images| grep jenkins
my_jenkins           0.0.2               90f8410b7770        5 seconds ago       737.7 MB
jenkins              1.651.3             d5c0410b1b44        3 weeks ago         736.9 MB
jenkins              latest              d5c0410b1b44        3 weeks ago         736.9 MB
```

**Comment by chouseknecht** [comment]
I'm not able to reproduce the error. 

Here's my test directory:

```
$ ls -l
total 24
-rw-r--r--  1 chouseknecht  staff  200 Jul 11 14:31 Dockerfile
-rw-r--r--  1 chouseknecht  staff   48 Jul 11 14:31 plugins.txt
-rw-r--r--  1 chouseknecht  staff  199 Jul 11 14:32 test_build.yml
```

Contents of the Dockerfile and plugins.txt are copy-paste from above. And the playbook...

```
- name: test image build
  connection: local
  hosts: localhost
  gather_facts: no
  tasks:
    - docker_image:
        name: my_jenkins
        path: .
        state: present
        tag: "0.0.2"
```

I'm running Docker Server version 1.11.1 via Docker Machine. I have docker-py 1.8.0 installed.

**Comment by dgjnpr** [comment]
Thanks for trying @chouseknecht 

After doing a more thorough debugging session I've finally got to the bottom of the problem. There is a race condition ultimately causes docker/client.py:233 to try an load a multiline string that contains multiple json objects. This is the root of my whole problem. 

So, good news, no bug with this module. Bad news for docker-py. I'll open an issue for this there.

Here's a stacktrace showing the error. I've modified docker-py to print the "chunks" it receives. You'll see that last printed line is a multiline output.

```
$ python docker_image execute
Traceback (most recent call last):
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 532, in <module>
    main()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 524, in main
    ImageManager(client, results)
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 244, in __init__
    self.present()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 273, in present
    self.results['image'] = self.build_image()
  File "/Users/dgethings/.ansible/tmp/ansible-tmp-1468925027.86-15206280689556/debug_dir/ansible_module_docker_image.py", line 458, in build_image
    for line in self.client.build(**params):
  File "/Library/Python/2.7/site-packages/docker/client.py", line 234, in _stream_helper
    data = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 4 column 1 (char 63 - 224)
debug: {"stream":"Step 1 : FROM jenkins:2.7.1-alpine\n"}
 :end
debug: {"status":"Pulling from library/jenkins","id":"2.7.1-alpine"}
{"status":"Digest: sha256:031c2be684f7aa8b50684ca9b0517e6b3d3f86912e879b77cfe5ef002581980d"}
{"status":"Status: Image is up to date for jenkins:2.7.1-alpine"}
 :end
```
