### ISSUE TITLE
ziploader lock failure

### ISSUE THREAD

**Issue by ryanlovett** [ansible/ansible-modules-core#4347]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

executor/module_common.py
ziploader
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I'm using the ansible ppa:

```
 *** 2.1.1.0-1ppa~trusty 0
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main amd64 Packages
```
##### CONFIGURATION

```
# egrep -v '^#|^$' /etc/ansible/ansible.cfg
[defaults]
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```
##### SUMMARY

Possibly related to this closed bug:
https://github.com/ansible/ansible-modules-core/issues/3504

This error happens every time I run ansible-playbook.
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  tasks:
  - name: do nothing
    command: /bin/true
```

The command was `ansible-playbook -vvvv /var/tmp/ansible/test.yml`.

##### EXPECTED RESULTS

No error.
##### ACTUAL RESULTS

```
# ansible-playbook -vvvv /var/tmp/ansible/test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yml *************************************************************
1 plays in /var/tmp/ansible/test.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 583, in _execute_module
    (module_style, shebang, module_data) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 149, in _configure_module
    (module_data, module_style, module_shebang) = modify_module(module_name, module_path, module_args, task_vars=task_vars, module_compression=self._play_context.module_compression)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 733, in modify_module
    (module_data, module_style, shebang) = _find_snippet_imports(module_name, module_data, module_path, module_args, task_vars, module_compression)
  File "/usr/lib/python2.7/dist-packages/ansible/executor/module_common.py", line 576, in _find_snippet_imports
    with lock:
AttributeError: __exit__

fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/var/tmp/ansible/test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1


```

**Comment by jctanner** [comment]
@yanlovett please file this under https://github.com/ansible/ansible/issues
