### ISSUE TITLE
include_vars_module: 

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible-modules-core#4375]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

include_vars_module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

``` ini
[defaults]
hostfile = ./inventory
retry_files_save_path = ./retry/
verbose = True
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
vault_password_file = vaultkeychain
callback_whitelist = timer
sudo_flags = -E -H -S -n
stdout_callback = skippy
display_skipped_hosts = False

[ssh_connection]
pipelining = True
```
##### OS / ENVIRONMENT

Mac OS
##### SUMMARY

include_vars fails with error
##### STEPS TO REPRODUCE

```
- name: read db config
  include_vars:
      file: "/tmp/config.json"
```

##### EXPECTED RESULTS

Vars loaded
##### ACTUAL RESULTS

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 124, in run
    res = self._execute()
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 448, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/include_vars.py", line 41, in run
    source = self._loader.path_dwim_relative(self._loader.get_basedir(), 'vars', source)
  File "/usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages/ansible/parsing/dataloader.py", line 236, in path_dwim_relative
    if source.startswith('~') or source.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

fatal: [test]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```
#### WORKAROUND

```
- name: read db config
  include_vars:
      file: "/tmp/config.json"
      _raw_params: "/tmp/config.json"
```

**Comment by hryamzik** [comment]
Oops, it's only supported in 2.2, closing.
