### ISSUE TITLE
eos_template: TypeError: load_config() got an unexpected keyword argument 'session'

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible-modules-core#4801]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

eos_template
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel 9868117d1f) last updated 2016/09/12 20:18:28 (GMT +100)
  lib/ansible/modules/core: (devel 432ee70da1) last updated 2016/09/12 20:19:14 (GMT +100)
  lib/ansible/modules/extras: (devel 67a1bebbd3) last updated 2016/09/12 12:05:15 (GMT +100)

```
##### SUMMARY

https://github.com/ansible/ansible-modules-core/commit/e464599632340f247c593f2db770be9782f7dec5
changed `module.config.load_config` to pass in `session` however that doesn't seem to be in https://github.com/ansible/ansible/blame/devel/lib/ansible/module_utils/netcfg.py#L56

@privateip When you ran
`ansible-playbook -vvv  eos.yaml`
Did you have other local changes
##### STEPS TO REPRODUCE

```
ansible-playbook -vvv  eos.yaml -i ../inventory-testnetwork   -e "limit_to=eos_template"
```
##### EXPECTED RESULTS

Tests to pass
##### ACTUAL RESULTS

```
TASK [test_eos_template : configure device with config] ************************
task path: /home/johnb/git/ansible-inc/test-network-modules/roles/test_eos_template/tests/cli/force.yaml:14
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/core/network/eos/eos_template.py
<veos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<veos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673 `" && echo ansible-tmp-1473707985.23-162291198567673="` echo $HOME/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673 `" ) && sleep 0'
<veos01> PUT /tmp/tmpsPqOzL TO /home/johnb/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673/eos_template.py
<veos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673/ /home/johnb/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673/eos_template.py && sleep 0'
<veos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673/eos_template.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1473707985.23-162291198567673/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aJfsia/ansible_module_eos_template.py", line 215, in <module>
    main()
  File "/tmp/ansible_aJfsia/ansible_module_eos_template.py", line 205, in main
    commit=True)
  File "/tmp/ansible_aJfsia/ansible_modlib.zip/ansible/module_utils/netcfg.py", line 58, in load_config
TypeError: load_config() got an unexpected keyword argument 'session'

```

**Comment by gundalow** [comment]
Now passes with

```
ansible 2.2.0 (devel 036650cb09) last updated 2016/09/13 09:18:44 (GMT +100)
  lib/ansible/modules/core: (devel ae6992bf8c) last updated 2016/09/13 09:19:01 (GMT +100)
  lib/ansible/modules/extras: (devel 1f6f3b72db) last updated 2016/09/13 09:19:10 (GMT +100)

```
