### ISSUE TITLE
Error using gc_storage

### ISSUE THREAD

**Issue by abadger** [ansible/ansible-modules-core#500]
Copied from: https://github.com/ansible/ansible/issues/9794 by @Erouan50
##### Issue Type:

Bug Report
##### Ansible Version:

1.7.2
##### Environment:
- Runing on Fedora 20 (kernel 3.17.4-200.fc20.x86_64)
- Managing on localhost
##### Summary:

I'm using the gc_storage to create new buckets with a directory object. Here the task :

``` yaml
- name: Create Bucket to store database wall
    gc_storage:
      gs_access_key: "{{gcs_access_key}}"
      gs_secret_key: "{{gcs_secret_key}}"
      bucket: "postgres-wall"
      object: "/{{client_name}}-{{client_env}}"
      mode: "create"
```

When I run the playbook I get this error :

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 1766, in <module>
    main()
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 395, in main
    handle_create(module, gs, bucket, obj)
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 333, in handle_create
    create_dirkey(module, gs, bucket, dirobj)
UnboundLocalError: local variable 'dirobj' referenced before assignment
```

But when I run again the playbook, the task succeed.
##### Steps To Reproduce:

Should succeed.
##### Actual Results:

The results:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 1766, in <module>
    main()
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 395, in main
    handle_create(module, gs, bucket, obj)
  File "/home/erouan/.ansible/tmp/ansible-tmp-1418382695.99-246253342676237/gc_storage", line 333, in handle_create
    create_dirkey(module, gs, bucket, dirobj)
UnboundLocalError: local variable 'dirobj' referenced before assignment
```

Thanks,
Antoine Rouaze

**Comment by abadger** [comment]
@Erouan50 - could you test this fix and let us know if it is still broken?  I don't have a gce account to see whether it works but it should solve address the traceback.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
