### ISSUE TITLE
error creating ec2 metric alarms when there are different dimensions ansible -1.8.2

### ISSUE THREAD

**Issue by rajofchennai** [ansible/ansible-modules-core#516]
##### Steps To Reproduce:

```
- name: create alarm
  ec2_metric_alarm:
    state: present
    region: us-west-2
    name: "disk space low"
    metric: "DiskSpaceUtilization"
    namespace: "System/Linux"
    statistic: Average
    comparison: ">="
    threshold: 80.0
    period: 300
    evaluation_periods: 3
    unit: "Percent"
    description: "When disk usage becomes more than 80% alerts concerned folks :)"
    dimensions: { "InstanceId": "{{ instance_id }}" , "Filesystem": "/dev/xvda1" }
    alarm_actions: ["<sns url>"]
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
```
##### Actual Results:

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1418647479.92-52175158111944/ec2_metric_alarm", line 2040, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1418647479.92-52175158111944/ec2_metric_alarm", line 2036, in main
    create_metric_alarm(connection, module)
  File "/root/.ansible/tmp/ansible-tmp-1418647479.92-52175158111944/ec2_metric_alarm", line 1951, in create_metric_alarm
    if dim1[keys] != dim2[keys]:
KeyError: 'Filesystem'
```

**Comment by bennojoy** [comment]
@rajofchennai  i am not able to reproduce this in 1.9.x, can you please try with the latest devel branch.

**Comment by bennojoy** [comment]
@rajofchennai friendly ping to check if you were able to reproduce this..

**Comment by bennojoy** [comment]
closing as there is no response and the issue is not reproducible.
