### ISSUE TITLE
TypeError: run_command() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible-modules-core#5538]
Module: shell
ansible 2.2.0.0

```
- hosts: consul
  serial: 2
  become: true

  pre_tasks:
  - name: restart consul
    shell: 'killall -9 consul; service consul start'    #I know its bad style
```

There is an error
I did try to debug it debug it 'in place'  with export ANSIBLE_KEEP_REMOTE_FILES=1

```
/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1478682342.04-18662951438118/command.py
Traceback (most recent call last):
  File "/tmp/ansible_4J25XG/ansible_module_command.py", line 212, in <module>
    main()
  File "/tmp/ansible_4J25XG/ansible_module_command.py", line 189, in main
    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)
TypeError: run_command() got an unexpected keyword argument 'encoding'
```

1) The issue itself - any ideas?
2) Shebang - I know I am the author of the idea of 'appending the 'egg' or external module library into the ansible exec :) but is there a way of 'shebang'ing' the ZIPDATA as plain text?

**Comment by sirkubax** [comment]
2 - I've found it in the code :+1: great
**explode**
/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1478682342.04-18662951438118/command.py explode

**Comment by sirkubax** [comment]
the line 189 of exploded file (/home/ubuntu/.ansible/tmp/ansible-tmp-1478682342.04-18662951438118/debug_dir/ansible_module_command.py)
rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)

args:
killall -9 consul; service consul start

Now I need to dig into module.run_command()

**Comment by sirkubax** [comment]
[SOLVED] - some version mismatch!

The file:
/home/ubuntu/.ansible/tmp/ansible-tmp-1478682342.04-18662951438118/debug_dir/ansible_module_command.py

> >    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)

Was inconsistent with the core modules:
/home/ubuntu/.ansible/tmp/ansible-tmp-1478682342.04-18662951438118/debug_dir/ansible/module_utils/basic.py
(look for encoding keyword)

```
    def run_command(self, args, check_rc=False, close_fds=True, executable=None, data=None, binary_data=False, path_prefix=None, cwd=None, use_unsafe_shell=False, prompt_regex=None, environ_update=None, umask=None):
        '''

```

**Explanation:**
I was installing the ansible in virtualenv, dirrectly from github:
https://github.com/ansible/ansible/archive/v2.2.0.0-0.1.rc1.tar.gz
https://github.com/ansible/ansible-modules-extras/archive/stable-2.2.zip
https://github.com/ansible/ansible-modules-core/archive/stable-2.2.zip

bad idea of installing packets:

_pip install https://github.com/ansible/ansible/archive/v2.2.0.0-0.1.rc1.tar.gz
mkdir tmp
wget https://github.com/ansible/ansible-modules-extras/archive/stable-2.2.zip -O tmp/stable-2.2.extras.zip
unzip tmp/stable-2.2.extras.zip -d tmp/
wget https://github.com/ansible/ansible-modules-core/archive/stable-2.2.zip -O tmp/stable-2.2.core.zip
unzip tmp/stable-2.2.core.zip -d tmp/
cp tmp/ansible-modules-extras-stable-2.2/ venv/lib/python2.7/site-packages/ansible/modules/extras/ -a
cp tmp/ansible-modules-core-stable-2.2/ venv/lib/python2.7/site-packages/ansible/modules/core/ -a_

Works with - installing all directly from git
git+git://github.com/ansible/ansible.git@stable-2.2

_pip install git+git://github.com/ansible/ansible.git@stable-2.2_

**Comment by sirkubax** [comment]
Closing the ticket :)
