### ISSUE TITLE
NameError: global name 'docker' is not defined

### ISSUE THREAD

**Issue by mankind** [ansible/ansible-modules-core#683]
**Issue Type:**
    Bug Report

**Ansible Version:**

```
   ansible 1.9 (devel 46b29c3f4b) last updated 2015/01/21 22:45:12 (GMT +100)
   lib/ansible/modules/core: (detached HEAD 396c399b54) last updated 2015/01/21 22:45:21 (GMT +100)
   lib/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/21 22:45:30 (GMT +100)
   v2/ansible/modules/core: (detached HEAD 8ba8f5ef4d) last updated 2015/01/21 22:45:39 (GMT +100)
   v2/ansible/modules/extras: (detached HEAD 2396f36f11) last updated 2015/01/21 22:45:45 (GMT +100)
    configured module search path = /usr/share/ansible
```

**Environment:**

```
 Ubuntu 13.10
 Docker-py (0.7.1) 
 Docker version 1.4.1, build 5bc2ff8
```

**Summary:**

Using the docker module in a playbook and running that playbook returns the error below:

```
    TASK: [Run Docker private registry] ******************************************* 
    failed: [localhost] => {"failed": true, "parsed": false}
    SUDO-SUCCESS-bomqzjizfwqbuvuvurlcknjmzfygsfvo
    Traceback (most recent call last):
    File "/home/.ansible/tmp/ansible-tmp-1421886278.27-   209846179492524/docker", line 2543, in <module>
    main()
    File "/home/.ansible/tmp/ansible-tmp-1421886278.27-209846179492524/docker", line 848, in main
    docker_api_version = dict(default=docker.client.DEFAULT_DOCKER_API_VERSION),
    NameError: global name 'docker' is not defined
    FATAL: all hosts have already failed -- aborting

     PLAY RECAP ******************************************************************** 
       to retry, use: --limit @/home/registry.retry
        localhost                  : ok=2    changed=0    unreachable=0    failed=1 
```

**Steps To Reproduce:**

```
       ---
       - name: Using ansible to update docker 
         hosts: local
         sudo: yes

         tasks: 
          - name: Run Docker private registry
            docker:
               docker_api_version: 1.16
               image: registry
               state: running
               expose: 5000
               ports: "127.0.0.1:5000:5000"
               volumes:  "~/docker/registry-storage:/var/www:ro"
               env: "STORAGE_PATH=~/docker/registry-storage"
```

**Expected Results:**

```
      TASK: [Run Docker private registry] *********************************
       ok: [localhost]
```

**Actual Results:**

The error thrown is already pasted in the summary section.

**Comment by bcoca** [comment]
it seems the docker python module is not installed, this is still a bug as checking for the docker module happens after attempts to use it.

**Comment by mankind** [comment]
Thanks @bcoca  for looking at it. I installed **docker python module** with sudo pip install docker-py and confirmed it was installed by checking **pip list**.
