### ISSUE TITLE
ec2_asg with tags completely broken

### ISSUE THREAD

**Issue by m-o-e** [ansible/ansible-modules-core#744]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.8 (devel 547c0d8140) last updated 2014/10/27 18:11:04 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 7f611468a8) last updated 2014/10/27 18:11:10 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD a0df36c6ab) last updated 2014/10/27 18:11:15 (GMT +200)
  v2/ansible/modules/core: (detached HEAD cb69744bce) last updated 2014/10/27 18:11:21 (GMT +200)
  v2/ansible/modules/extras: (detached HEAD 8a4f07eecd) last updated 2014/10/27 18:11:26 (GMT +200)
  configured module search path = None
```
##### Environment:

Linux
##### Summary:

ec2_asg fails spectacularly when it is used with a _tags_ argument.
##### Steps To Reproduce:

Any ec2_asg task that has a _tags_ argument will trigger this bug, e.g.:

``` yaml
- ec2_asg:
    name: foo
    launch_config_name: 'lc-1'
    min_size: 1
    max_size: 1
    desired_capacity: 1
    vpc_zone_identifier: [ 'subnet-abcd1234' ]
    tags:
      - foo: bar
```
##### Expected Results:

The ASG should be created if missing. Otherwise the task should be skipped.
##### Actual Results:

Ansible will fail in one of two ways, depending on whether
any tagged auto scaling groups exist on AWS already.
##### Case 1: No tagged ASG  exists on AWS yet

Ansible will successfully create the requested ASG and
immediately afterwards fail with the following error:

```
TASK: [cluster_asg | ec2_asg ] *************************************************
failed: [cluster_asg] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/moe/.ansible/tmp/ansible-tmp-1422991199.84-118626399276493/ec2_asg", line 2324, in <module>
    main()
  File "/home/moe/.ansible/tmp/ansible-tmp-1422991199.84-118626399276493/ec2_asg", line 2314, in main
    create_changed, asg_properties=create_autoscaling_group(connection, module)
  File "/home/moe/.ansible/tmp/ansible-tmp-1422991199.84-118626399276493/ec2_asg", line 2054, in create_autoscaling_group
    existing_tag_map = dict((tag.key, tag) for tag in existing_tags)
  File "/home/moe/.ansible/tmp/ansible-tmp-1422991199.84-118626399276493/ec2_asg", line 2054, in <genexpr>
    existing_tag_map = dict((tag.key, tag) for tag in existing_tags)
AttributeError: 'dict' object has no attribute 'key'
```
##### Case 2: At least one tagged ASG exists on AWS already

Ansible will fail with the following error:

```
TASK: [cluster_asg | ec2_asg ] *************************************************
failed: [cluster_asg] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/moe/.ansible/tmp/ansible-tmp-1422990578.86-201224704818227/ec2_asg", line 2324, in <module>
    main()
  File "/home/moe/.ansible/tmp/ansible-tmp-1422990578.86-201224704818227/ec2_asg", line 2322, in main
    module.exit_json( changed = changed, **asg_properties )
  File "/home/moe/.ansible/tmp/ansible-tmp-1422990578.86-201224704818227/ec2_asg", line 1388, in exit_json
    print self.jsonify(kwargs)
  File "/home/moe/.ansible/tmp/ansible-tmp-1422990578.86-201224704818227/ec2_asg", line 1366, in jsonify
    return json.dumps(data)
  File "/home/moe/code/px/sys/python/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/home/moe/code/px/sys/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/moe/code/px/sys/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/moe/code/px/sys/python/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Tag(cluster=crunch2) is not JSON serializable
```

Case 2 looks similar to https://github.com/ansible/ansible-modules-core/issues/274

**Comment by m-o-e** [comment]
This issue (and a slew of others) should now be fixed in PR https://github.com/ansible/ansible-modules-core/pull/745

**Comment by tomstockton** [comment]
:+1: I would like to use tags with autoscaling groups too.

**Comment by m-o-e** [comment]
I'm not sure why its not getting merged, I'll add a bump on the PR.
