### ISSUE TITLE
uri.py : Traceback when there is a special character in the JSON return

### ISSUE THREAD

**Issue by francoisfanuel** [ansible/ansible-modules-core#805]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.8.2
##### Environment:

MacOS X 10.10.2
##### Summary:

Using uri module, when the return of a webservice call is a JSON with a special character in it, it fails with this error message : "ValueError: Invalid control character at: line 1 column x (char x-1)"

Example when the return is : 
{"jsonrpc": "2.0", "result": [{"messages": ["verify /sha512 (flash:test) = abe28fc99538f10f44df793ddd272ddd5484a07a8d4b9988305c68cfb4ecad76579271f5bbaaea2b7458cd7b407615e38e2ac6940fb8d760f02729548eb44695\n"]}], "id": "toto"}

The playbooks fails with this error : 
Traceback (most recent call last):
  File "/Users/francoisfanuel/.ansible/tmp/ansible-tmp-1424265104.5-7980688633469/uri", line 2011, in <module>
    main()
  File "/Users/francoisfanuel/.ansible/tmp/ansible-tmp-1424265104.5-7980688633469/uri", line 432, in main
    js = json.loads(content)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 1 column 204 (char 203)
##### Fix:

In uri.py, change the call to json.loads to:
                js = json.loads(content,strict=False)

On line 432.

**Comment by bcoca** [comment]
just merged #537, could you check if it fixes this issue also?

**Comment by francoisfanuel** [comment]
Hi,
Yes, that fixes the issue too.
Thanks a lot.

François

**Comment by abadger** [comment]
This should have been fixed in ansible/ansible-modules-core#537 however there are some other issues with that code. I've just submitted ansible/ansible-modules-core#1331 to try to fix those issues. If anyone is still interested in this, please test that PR to be sure it doesn't cause a regression in this fix.
