### ISSUE TITLE
NameError: global name 'tenancy' is not defined

### ISSUE THREAD

**Issue by viatcheslavmogilevsky** [ansible/ansible-modules-core#808]
**Issue Type:**
Bug Report

**Ansible Version:**
1.8.3

**Environment:**
Ubuntu 14.04  kernel: 3.13.0-45-generic

**Summary:**
Cannot to create new AWS EC2 instance using ec2 module, the following failure is raised:
NameError: global name 'tenancy' is not defined

**Steps To Reproduce:**
1) Have playbook like:

``` yaml
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    # security groups, VPCs, and so on

    - ec2:
        region: "{{ aws_region }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
        key_name: "{{ aws_key_name }}"
        instance_type: "{{ item.instance_type }}"
        instance_tags:
          Name: "{{ item.name }}"
        image: "{{ item.image }}"
        wait: yes
        group: "{{ item.name }}"
        exact_count: 1
        count_tag:
          Name: "{{ item.name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      with_items:
        - name: existing_server1
          image: ami-f0b11187
          instance_type: t2.micro
        - name: existing_server2
          image: ami-f0b11187
          instance_type: t2.micro
        - name: new-server
          image: ami-f0b11187
          instance_type: t2.micro
```

2)run this playbook

``` bash
ansible-playbook  stack.yml
```

**Expected Results:**
EC2 instance with tag Name: new-server is successfully created

**Actual Results:**

``` plain
ok: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'existing_server1'})
ok: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'existing_server2'})
failed: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'new-server'}) => {"failed": true, "item": {"image": "ami-f0b11187", "instance_type": "t2.micro", "name": "new-server"}, "parsed": false}
Traceback (most recent call last):
  File "/home/provectus/.ansible/tmp/ansible-tmp-1424268793.19-187172363730612/ec2", line 2998, in <module>
    main()
  File "/home/provectus/.ansible/tmp/ansible-tmp-1424268793.19-187172363730612/ec2", line 1203, in main
    (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
  File "/home/provectus/.ansible/tmp/ansible-tmp-1424268793.19-187172363730612/ec2", line 682, in enforce_count
    = create_instances(module, ec2, override_count=to_create)
  File "/home/provectus/.ansible/tmp/ansible-tmp-1424268793.19-187172363730612/ec2", line 817, in create_instances
    params['tenancy'] = tenancy
NameError: global name 'tenancy' is not defined
```

**Comment by viatcheslavmogilevsky** [comment]
I just have rollback ansible to version: 1.7.2+dfsg-1~ubuntu14.04.1 (which is last on my apt cache)
and then it works properly:

``` plain
TASK: [ec2 ] ****************************************************************** 
ok: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'existing_server1'})
ok: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'existing_server2'})
changed: [localhost] => (item={'instance_type': 't2.micro', 'image': 'ami-f0b11187', 'name': 'new-server'})

```

**Comment by abadger** [comment]
This looks like it was because we pulled one commit from devel to the 1.8.3 release by mistake.  It relied on some new features that we didn't want to introduce into a stable series.  We're going to look for other major bugs in 1.8.3 and then push out a 1.8.4 with a fix for this and any of those things that we find.

**Comment by juliedavila** [comment]
Confirming that I have the same issue.

**Comment by abadger** [comment]
1.8.4 released which should have fixed this.

**Comment by viatcheslavmogilevsky** [comment]
Thanks all for instant fix)
