### ISSUE TITLE
EC2 host launch fails

### ISSUE THREAD

**Issue by rhartkopf** [ansible/ansible-modules-core#817]
EC2 instance launching appears to be broken for me in Ansible 1.8.3. Error:

```
failed: [dev.example.com -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424304056.45-134380261320364/ec2", line 2998, in <module>
    main()
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424304056.45-134380261320364/ec2", line 1203, in main
    (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424304056.45-134380261320364/ec2", line 682, in enforce_count
    = create_instances(module, ec2, override_count=to_create)
  File "/var/lib/jenkins/.ansible/tmp/ansible-tmp-1424304056.45-134380261320364/ec2", line 817, in create_instances
    params['tenancy'] = tenancy
NameError: global name 'tenancy' is not defined
```

Launch params:

```
  - name: find or provision ec2 instance
    local_action:
      module: ec2
      key_name: "ansible"
      instance_type: "t2.micro"
      image: "ami-076e6542"
      wait: yes
      assign_public_ip: yes
      wait_timeout: 300
      group_id: "sg-ad9838c8"
      region: "us-west-1"
      instance_tags:
        Name: "dev.example.com"
        Subnet: "Dev"
      exact_count: 1
      count_tag:
        Name: "dev.example.com"
      vpc_subnet_id: "subnet-53021b15}"
    register: my_instance
```

The issues appear to be with 7724112, 7c42182, and df53b85. Launch works fine in v1.8.2.

Let me know if you need any additional info about my AWS env, or if this is required now and I should submit a PR for the docs.

**Comment by rhartkopf** [comment]
I just realized those 3 commits were made after the submodule update for v1.8.3. I'll test against the latest commits first.

**Comment by rhartkopf** [comment]
Correction, HEAD works fine. v1.8.3 submodule is tagged at 6bed6e6, which is broken.

Closing.
